#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Collect static assets for Whitenoise before launching the server
python /app/manage.py collectstatic --noinput

# Run migrations
python /app/manage.py migrate

# Start development server
exec python /app/manage.py runserver 0.0.0.0:8000
