"""Create a promoted schema manifest that surfaces canonical relationships.

The existing Folkwang mapping still references legacy Kreuztabelle predicates.
This command clones the mapping configuration for the selected organization
and appends columns + FK metadata for the derived predicates generated by the
``promote_legacy_junctions`` command. The promoted manifest is persisted under
``mapping_config[output_key]`` so forms can opt-in without mutating the
validated source manifest.
"""

from __future__ import annotations

import copy
from datetime import datetime, timezone
from typing import Dict, Iterable, Optional

from django.core.management.base import BaseCommand, CommandError

from arkumu.metadata.models.mappings import Mapping
from arkumu.metadata.models import Resource
from arkumu.users.models import Organization


TARGET_ID_CANONICAL = {
    "Projekt": "http://arkumu.org/data/properties/projekt-id",
    "AkteurIn": "http://arkumu.org/data/properties/akteurin-id",
    "Ereignis": "http://arkumu.org/data/properties/ereignis-id",
    "Rolle": "http://arkumu.org/data/properties/rolle-id",
}


PROMOTED_RELATIONS = [
    {
        "dataset": "Projekt",
        "column_name": "Projekt hat Teil",
        "canonical_predicate": "http://arkumu.org/data/properties/projekt-hat-teil",
        "target_dataset": "Projekt",
        "target_column": "Projekt-ID",
        "is_multi_value": True,
        "id_suffix": "projekt-hat-teil",
    },
    {
        "dataset": "Projekt",
        "column_name": "Projekt ist Teil von",
        "canonical_predicate": "http://arkumu.org/data/properties/projekt-ist-teil-von",
        "target_dataset": "Projekt",
        "target_column": "Projekt-ID",
        "is_multi_value": True,
        "id_suffix": "projekt-ist-teil-von",
    },
    {
        "dataset": "Projekt",
        "column_name": "Projekt hat Bezug zu",
        "canonical_predicate": "http://arkumu.org/data/properties/projekt-hat-bezug-zu",
        "target_dataset": "Projekt",
        "target_column": "Projekt-ID",
        "is_multi_value": True,
        "id_suffix": "projekt-hat-bezug-zu",
    },
    {
        "dataset": "Projekt",
        "column_name": "Projekt basiert auf",
        "canonical_predicate": "http://arkumu.org/data/properties/projekt-basiert-auf",
        "target_dataset": "Projekt",
        "target_column": "Projekt-ID",
        "is_multi_value": True,
        "id_suffix": "projekt-basiert-auf",
    },
    {
        "dataset": "Projekt",
        "column_name": "Projekt ist vorbereitend für",
        "canonical_predicate": "http://arkumu.org/data/properties/projekt-ist-vorbereitend-fuer",
        "target_dataset": "Projekt",
        "target_column": "Projekt-ID",
        "is_multi_value": True,
        "id_suffix": "projekt-ist-vorbereitend-fuer",
    },
    {
        "dataset": "Ereignis",
        "column_name": "Ereignis hat AkteurIn",
        "canonical_predicate": "http://arkumu.org/data/properties/ereignis-hat-akteurin",
        "target_dataset": "AkteurIn",
        "target_column": "AkteurIn-ID",
        "is_multi_value": True,
        "id_suffix": "ereignis-hat-akteurin",
    },
    {
        "dataset": "AkteurIn",
        "column_name": "AkteurIn wirkt in Ereignis",
        "canonical_predicate": "http://arkumu.org/data/properties/akteurin-im-ereignis",
        "target_dataset": "Ereignis",
        "target_column": "Ereignis-ID",
        "is_multi_value": True,
        "id_suffix": "akteurin-im-ereignis",
    },
    {
        "dataset": "AkteurIn_Ereignis_Kreuztabelle",
        "column_name": "Rolle im Ereignis",
        "canonical_predicate": "http://arkumu.org/data/properties/akteurin-hat-rolle-im-ereignis",
        "target_dataset": "Rolle",
        "target_column": "Rolle-ID",
        "is_multi_value": True,
        "id_suffix": "akteurin-hat-rolle-im-ereignis",
    },
]


class Command(BaseCommand):
    """Clone mapping config and add promoted relationship columns."""

    def add_arguments(self, parser):  # pragma: no cover - argparse boilerplate
        parser.add_argument(
            "--organization",
            "-o",
            required=True,
            help="Organization code to process",
        )
        parser.add_argument(
            "--output-key",
            default="promoted_manifest",
            help="Dictionary key to store the promoted manifest (default: promoted_manifest)",
        )

    def handle(self, *args, **options):
        org_code: str = options["organization"].lower()
        output_key: str = options["output_key"]

        try:
            organization = Organization.objects.get(code=org_code)
        except Organization.DoesNotExist as exc:
            raise CommandError(f"Organization '{org_code}' not found") from exc

        mapping = Mapping.objects.filter(organization_id=organization.code).first()
        if not mapping:
            raise CommandError(f"No mapping configuration found for organization '{org_code}'")

        config = mapping.mapping_config
        required_keys = {"workspace_columns", "schema_manifest", "fk_relationships"}
        if not required_keys.issubset(config.keys()):
            missing = required_keys - set(config.keys())
            raise CommandError(f"Mapping config missing required sections: {', '.join(sorted(missing))}")

        promoted_workspace_columns = copy.deepcopy(config["workspace_columns"])
        promoted_schema_manifest = copy.deepcopy(config["schema_manifest"])
        promoted_fk_relationships = copy.deepcopy(config["fk_relationships"])

        timestamp = datetime.now(timezone.utc).isoformat()

        additions = []
        for spec in PROMOTED_RELATIONS:
            property_resource = self._get_property_resource(organization, spec["canonical_predicate"])
            if not property_resource:
                self.stdout.write(
                    self.style.WARNING(
                        f"Skipping {spec['canonical_predicate']} (resource not found)"
                    )
                )
                continue

            column_id = f"promoted::{spec['dataset']}::{spec['id_suffix']}"
            if column_id in promoted_workspace_columns:
                continue

            promoted_workspace_columns[column_id] = {
                "id": column_id,
                "name": spec["column_name"],
                "type": "string",
                "is_fk": True,
                "source": spec["dataset"],
                "dataset": spec["dataset"],
                "added_at": timestamp,
                "is_anchor": False,
                "is_multi_value": spec["is_multi_value"],
                "fk_config": {
                    "direction": "outbound",
                    "target_column": spec["target_column"],
                    "target_dataset": spec["target_dataset"],
                },
            }

            self._inject_schema_manifest_entry(
                promoted_schema_manifest,
                spec,
                property_resource.uri,
                property_resource.canonical_uri,
                organization,
            )

            fk_key = column_id
            promoted_fk_relationships[fk_key] = {
                "direction": "outbound",
                "source_column": spec["column_name"],
                "source_dataset": spec["dataset"],
                "target_column": spec["target_column"],
                "target_dataset": spec["target_dataset"],
                "display_column": None,
                "relationship_type": spec["column_name"],
            }

            additions.append(spec["column_name"])

        if not additions:
            self.stdout.write(self.style.WARNING("No promoted relationships added."))
            return

        config[output_key] = {
            "workspace_columns": promoted_workspace_columns,
            "schema_manifest": promoted_schema_manifest,
            "fk_relationships": promoted_fk_relationships,
            "created_at": timestamp,
        }

        mapping.mapping_config = config
        mapping.save(update_fields=["mapping_config"])

        self.stdout.write(
            self.style.SUCCESS(
                f"Promoted manifest stored under '{output_key}' with {len(additions)} relationship(s)."
            )
        )

    # ------------------------------------------------------------------
    # Helper utilities
    # ------------------------------------------------------------------

    def _get_property_resource(
        self,
        organization: Organization,
        canonical_uri: str,
    ) -> Optional[Resource]:
        return (
            Resource.objects.filter(canonical_uri=canonical_uri, organization=organization).first()
            or Resource.objects.filter(canonical_uri=canonical_uri, organization__isnull=True).first()
        )

    def _inject_schema_manifest_entry(
        self,
        manifest: Dict,
        spec: Dict,
        property_uri: str,
        canonical_uri: str,
        organization: Organization,
    ) -> None:
        dataset_entry = manifest.get(spec["dataset"])
        if not dataset_entry:
            return

        dataset_entry.setdefault("properties", {})[spec["column_name"]] = {
            "uri": property_uri,
            "name": spec["column_name"],
            "canonical_uri": canonical_uri,
        }

        target_canonical = TARGET_ID_CANONICAL.get(spec["target_dataset"])
        target_property_uri = None
        if target_canonical:
            target_prop = self._get_property_resource(organization, target_canonical)
            target_property_uri = target_prop.uri if target_prop else None

        fk_entry = {
            "source_column": spec["column_name"],
            "target_column": spec["target_column"],
            "is_multi_value": spec["is_multi_value"],
            "source_dataset": spec["dataset"],
            "target_dataset": spec["target_dataset"],
            "source_property": spec["column_name"],
            "relationship_type": spec["column_name"],
            "source_property_uri": property_uri,
            "source_canonical_property": canonical_uri,
            "target_property_uri": target_property_uri,
            "target_canonical_property": target_canonical,
        }

        fk_list = dataset_entry.setdefault("fk_relationships", [])
        # Avoid duplicates
        if not any(entry.get("source_column") == spec["column_name"] for entry in fk_list):
            fk_list.append(fk_entry)
