# Generated by Django 5.0.11 on 2025-11-04 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_previewimages_content_length_and_more'), ('catalog', '0003_alter_previewimages_options_and_more'), ('catalog', '0004_alter_previewimages_last_download'), ('catalog', '0005_alter_previewimages_last_download')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Path in S3')),
                ('img', models.BinaryField(help_text='Image Binary Data')),
                ('content_length', models.IntegerField(default=0, help_text='HTTP Content Length')),
                ('content_type', models.CharField(default=' ', help_text='HTTP Content Type')),
                ('last_download', models.DateTimeField(default=datetime.datetime(2025, 11, 4, 14, 37, 41, 727871, tzinfo=datetime.timezone.utc), help_text='Last Downloaded')),
                ('bucket', models.CharField(default='none', help_text='Bucket in S3')),
            ],
            options={
                'verbose_name': 'Preview Images',
                'verbose_name_plural': 'Preview Images',
                'ordering': ['bucket', 'path'],
                'indexes': [models.Index(fields=['bucket', 'path'], name='catalog_pre_bucket_5eeafb_idx')],
                'unique_together': {('bucket', 'path')},
            },
        ),
    ]
