# Generated by Django 5.0.11 on 2025-11-10 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_squashed_0005_alter_previewimages_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimages',
            name='bucket',
            field=models.CharField(help_text='Bucket in S3'),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='content_length',
            field=models.IntegerField(help_text='HTTP Content Length'),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='content_type',
            field=models.CharField(help_text='HTTP Content Type'),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 9, 40, 10, 319242, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
    ]
