# Generated by Django 5.0.11 on 2025-11-26 13:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_project_index_tables'),
        ('metadata', '0016_add_s3fileobject_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 13, 27, 32, 7788, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
        migrations.CreateModel(
            name='ProjectDetailIndex',
            fields=[
                ('project_resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_detail_index', serialize=False, to='metadata.resource')),
                ('uri', models.URLField(max_length=512, unique=True)),
                ('org_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('public_access_level', models.CharField(choices=[('private', 'Private - Organization only'), ('restricted', 'Restricted - Authenticated users only'), ('public', 'Public - Catalog display allowed')], default='restricted', max_length=20)),
                ('is_public_approved', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, default='')),
                ('subtitle', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('institution_label', models.TextField(blank=True, default='')),
                ('institution_uri', models.URLField(blank=True, default='', max_length=512)),
                ('project_type_label', models.TextField(blank=True, default='')),
                ('year_range', models.CharField(blank=True, default='', max_length=64)),
                ('categories', models.JSONField(default=list)),
                ('actors', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('digital_objects', models.JSONField(default=list)),
                ('alternative_titles', models.JSONField(default=list)),
                ('catchphrases', models.JSONField(default=list)),
                ('properties', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict)),
                ('authority', models.JSONField(default=dict)),
                ('submitter', models.JSONField(default=dict)),
                ('licenses', models.JSONField(default=dict)),
                ('rights_status', models.JSONField(default=dict)),
                ('reference_only', models.BooleanField(default=False)),
                ('harvestable', models.BooleanField(default=True)),
                ('ownership_filtered', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_version', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'project_detail_index',
                'ordering': ['org_code', 'title'],
                'indexes': [models.Index(fields=['org_code', 'public_access_level', 'is_public_approved'], name='prj_detail_visibility_idx')],
            },
        ),
    ]
