# Generated by Django 5.0.11 on 2025-11-29 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_consolidate_project_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewimages',
            name='etag',
            field=models.CharField(blank=True, default='', help_text='MD5 hash for HTTP ETag header', max_length=32),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 15, 11, 35, 614530, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
    ]
