# Generated by Django 5.0.11 on 2025-12-01 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_etag_to_previewimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindex',
            name='canonical_rdf_xml',
            field=models.TextField(blank=True, default='', help_text='Pre-serialized RDF/XML of the canonical entity graph'),
        ),
        migrations.AddField(
            model_name='projectindex',
            name='institutional_rdf_xml',
            field=models.TextField(blank=True, default='', help_text='Pre-serialized RDF/XML of the institutional/org-specific entity graph'),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 16, 37, 29, 921962, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
    ]
