# Generated by Django 5.0.11 on 2025-12-01 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_add_rdf_xml_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 16, 43, 50, 105482, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
    ]
