# Generated by Django 5.0.11 on 2025-12-01 16:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_add_rdf_xml_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindex',
            name='dc_contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectindex',
            name='dc_creators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectindex',
            name='has_copyright_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectindex',
            name='has_neighbouring_rights_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='previewimages',
            name='last_download',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 16, 51, 12, 175050, tzinfo=datetime.timezone.utc), help_text='Last Downloaded'),
        ),
    ]
