"""
METS (Metadata Encoding and Transmission Standard) serializer for complete project graphs.

This module packages complete project graphs from the Arkumu knowledge graph
into METS format, embedding the full graph as RDF/XML for semantic completeness.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Dict, Any, Optional
import json

from arkumu.metadata.services.canonical_graph_service import CanonicalGraphService


# METS namespaces
METS_NS = "http://www.loc.gov/METS/"
XLINK_NS = "http://www.w3.org/1999/xlink"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
DC_NS = "http://purl.org/dc/elements/1.1/"
DCTERMS_NS = "http://purl.org/dc/terms/"
RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"


class METSSerializer:
    """
    METS serializer for complete project graphs.

    Packages complete project graphs as METS documents with:
    - Dublin Core descriptive metadata (dmdSec)
    - Technical metadata about the graph (techMD)
    - Complete graph as JSON-LD (dataStream)
    - Logical structure map (structMap)
    """

    def __init__(self, org_code: str):
        self.org_code = org_code
        self.graph_service = CanonicalGraphService(org_code=org_code)

    def serialize_resource(self, resource_uri: str, include_complete_graph: bool = True) -> str:
        """
        Serialize a resource as METS with complete graph.

        Args:
            resource_uri: URI of the resource to serialize
            include_complete_graph: Whether to include the complete graph with all relationships

        Returns:
            XML string of the METS document
        """
        # Get the complete entity graph
        graph = self.graph_service.get_entity_graph(
            resource_uri,
            include_incoming=True,
            expand_neighbors=include_complete_graph
        )

        # Build METS document
        mets = self._build_mets_root(resource_uri)

        # Add descriptive metadata section
        self._add_descriptive_metadata(mets, graph)

        # Add technical metadata section
        self._add_technical_metadata(mets, graph, include_complete_graph)

        # Add file section with graph data
        self._add_file_section(mets, graph)

        # Add structural map
        self._add_structural_map(mets, resource_uri)

        # Convert to string
        return ET.tostring(mets, encoding='unicode', xml_declaration=True)

    def _build_mets_root(self, resource_uri: str) -> ET.Element:
        """Build the root METS element with namespaces."""
        mets = ET.Element(
            f"{{{METS_NS}}}mets",
            {
                "xmlns:mets": METS_NS,
                "xmlns:xlink": XLINK_NS,
                "xmlns:xsi": XSI_NS,
                "xmlns:dc": DC_NS,
                "xmlns:dcterms": DCTERMS_NS,
                "xmlns:rdf": RDF_NS,
                "xsi:schemaLocation": f"{METS_NS} http://www.loc.gov/standards/mets/mets.xsd",
                "OBJID": resource_uri,
                "TYPE": "Arkumu Project Graph",
                "PROFILE": "arkumu-complete-graph-v1.0"
            }
        )

        # Add METS header
        mets_hdr = ET.SubElement(mets, f"{{{METS_NS}}}metsHdr", {
            "CREATEDATE": datetime.now(timezone.utc).isoformat(),
            "LASTMODDATE": datetime.now(timezone.utc).isoformat()
        })

        agent = ET.SubElement(mets_hdr, f"{{{METS_NS}}}agent", {
            "ROLE": "CREATOR",
            "TYPE": "OTHER",
            "OTHERTYPE": "SOFTWARE"
        })
        ET.SubElement(agent, f"{{{METS_NS}}}name").text = "Arkumu OAI-PMH Provider"
        ET.SubElement(agent, f"{{{METS_NS}}}note").text = "Generated by Arkumu Knowledge Graph System"

        return mets

    def _add_descriptive_metadata(self, mets: ET.Element, graph: Dict[str, Any]) -> None:
        """Add Dublin Core descriptive metadata section."""
        dmd_sec = ET.SubElement(mets, f"{{{METS_NS}}}dmdSec", {"ID": "DMD_001"})
        md_wrap = ET.SubElement(dmd_sec, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "DC",
            "MIMETYPE": "text/xml"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Build Dublin Core from graph
        dc_data = self._extract_dublin_core_from_graph(graph)

        # Create Dublin Core container
        dc_root = ET.SubElement(xml_data, "dublincore", {
            "xmlns": DC_NS,
            "xmlns:dcterms": DCTERMS_NS
        })

        for element, values in dc_data.items():
            for value in values:
                if element.startswith('dcterms:'):
                    elem_name = element.replace('dcterms:', '')
                    ET.SubElement(dc_root, f"{{{DCTERMS_NS}}}{elem_name}").text = value
                else:
                    elem_name = element.replace('dc:', '')
                    ET.SubElement(dc_root, f"{{{DC_NS}}}{elem_name}").text = value

    def _add_technical_metadata(self, mets: ET.Element, graph: Dict[str, Any], complete_graph: bool) -> None:
        """Add technical metadata about the graph."""
        tech_md = ET.SubElement(mets, f"{{{METS_NS}}}techMD", {"ID": "TECH_001"})
        md_wrap = ET.SubElement(tech_md, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "OTHER",
            "OTHERMDTYPE": "Arkumu Graph Metadata",
            "MIMETYPE": "application/json"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Technical metadata about the graph
        tech_info = {
            "graph_type": "complete" if complete_graph else "direct",
            "entity_count": len(graph.get("entities", [])),
            "edge_count": len(graph.get("edges", [])),
            "root_entity": graph.get("root_id"),
            "organization": self.org_code,
            "serialization_timestamp": datetime.now(timezone.utc).isoformat(),
            "format_version": "arkumu-graph-v1.0"
        }

        # Add as JSON
        tech_elem = ET.SubElement(xml_data, "technical_metadata")
        tech_elem.text = json.dumps(tech_info, indent=2)

    def _add_file_section(self, mets: ET.Element, graph: Dict[str, Any]) -> None:
        """Add file section containing the complete graph data."""
        file_sec = ET.SubElement(mets, f"{{{METS_NS}}}fileSec")
        file_grp = ET.SubElement(file_sec, f"{{{METS_NS}}}fileGrp", {"USE": "GRAPH_DATA"})

        # Add JSON-LD representation
        file_elem = ET.SubElement(file_grp, f"{{{METS_NS}}}file", {
            "ID": "GRAPH_JSONLD",
            "MIMETYPE": "application/ld+json",
            "USE": "GRAPH_SERIALIZATION"
        })

        # Embed the graph as JSON-LD
        f_content = ET.SubElement(file_elem, f"{{{METS_NS}}}FContent")
        xml_data = ET.SubElement(f_content, f"{{{METS_NS}}}xmlData")
        graph_elem = ET.SubElement(xml_data, "graph_data")
        graph_elem.text = json.dumps(graph, indent=2)

    def _add_structural_map(self, mets: ET.Element, resource_uri: str) -> None:
        """Add logical structure map."""
        struct_map = ET.SubElement(mets, f"{{{METS_NS}}}structMap", {
            "TYPE": "logical",
            "LABEL": "Arkumu Project Graph Structure"
        })

        # Top-level div for the project
        div = ET.SubElement(struct_map, f"{{{METS_NS}}}div", {
            "TYPE": "project",
            "LABEL": f"Project: {resource_uri}",
            "DMDID": "DMD_001",
            "ADMID": "TECH_001"
        })

        # Link to the graph data
        fptr = ET.SubElement(div, f"{{{METS_NS}}}fptr", {"FILEID": "GRAPH_JSONLD"})

    def _extract_dublin_core_from_graph(self, graph: Dict[str, Any]) -> Dict[str, list]:
        """Extract Dublin Core elements from the graph."""
        from ..formats.dublin_core import DublinCoreSerializer, DEFAULT_PREDICATE_MAP

        root_id = graph.get("root_id")
        edges = graph.get("edges", [])

        # Get literal edges for the root entity
        def pred(e: Dict[str, Any]) -> str:
            return e.get("predicate_canonical") or e.get("predicate_uri")

        def obj_value(e: Dict[str, Any]) -> Optional[str]:
            return e.get("object_value")

        root_literal_edges = [
            e for e in edges
            if e.get("subject_id") == root_id and e.get("object_value") is not None
        ]

        # Use the Dublin Core serializer
        serializer = DublinCoreSerializer(predicate_map=DEFAULT_PREDICATE_MAP)
        return serializer.serialize_from_triples(
            root_literal_edges,
            get_predicate=pred,
            get_object_value=obj_value
        )


__all__ = ["METSSerializer"]