"""
METS (Metadata Encoding and Transmission Standard) serializer for complete project graphs.

This module packages complete project graphs from the Arkumu knowledge graph
into METS format, embedding the full graph as RDF/XML for semantic completeness.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Dict, Any, Optional

from lxml import etree as ET

from arkumu.metadata.services.canonical_graph_service import CanonicalGraphService


# METS namespaces
METS_NS = "http://www.loc.gov/METS/"
METS_SCHEMA_URL = "http://www.loc.gov/standards/mets/mets.xsd"
XLINK_NS = "http://www.w3.org/1999/xlink"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
DC_NS = "http://purl.org/dc/elements/1.1/"
DCTERMS_NS = "http://purl.org/dc/terms/"
RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"


def _escape_flocat_href(value: Optional[str]) -> Optional[str]:
    """Percent-encode square brackets for METS FLocat href values."""
    if not value:
        return value
    text = str(value)
    if not text:
        return text
    return text.replace('[', '%5B').replace(']', '%5D')


class METSSerializer:
    """
    METS serializer for complete project graphs.

    Packages complete project graphs as METS documents with:
    - Dublin Core descriptive metadata (dmdSec)
    - Technical metadata about the graph (techMD)
    - Complete graph as JSON-LD (dataStream)
    - Logical structure map (structMap)
    """

    def __init__(self, org_code: str, graph_service: Optional[CanonicalGraphService] = None):
        self.org_code = org_code
        self.graph_service = graph_service or CanonicalGraphService(org_code=org_code)

    def serialize_resource(self, resource_uri: str, include_complete_graph: bool = True) -> str:
        """
        Serialize a resource as METS with complete graph.

        Args:
            resource_uri: URI of the resource to serialize
            include_complete_graph: Whether to include the complete graph with all relationships

        Returns:
            XML string of the METS document
        """
        # Get the complete entity graph
        graph = self.graph_service.get_entity_graph(
            resource_uri,
            include_incoming=True,
            expand_neighbors=include_complete_graph
        )

        # Return empty string if no graph data or missing root_id
        if not graph or not graph.get("root_id"):
            return ""

        # Build METS document
        mets = self._build_mets_root(resource_uri)

        # Add descriptive metadata section
        self._add_descriptive_metadata(mets, graph)

        # Add technical metadata section
        self._add_technical_metadata(mets, graph, include_complete_graph)

        # Add file section with graph data and content locations
        self._add_file_section(mets, graph, resource_uri)

        # Add structural map
        self._add_structural_map(mets, resource_uri)

        # Convert to string
        return ET.tostring(mets, encoding='utf-8', xml_declaration=True).decode('utf-8')

    def _build_mets_root(self, resource_uri: str) -> ET.Element:
        """Build the root METS element with namespaces."""
        # Register namespaces to control prefixes and avoid duplicates
        ET.register_namespace("mets", METS_NS)
        ET.register_namespace("xlink", XLINK_NS)
        ET.register_namespace("xsi", XSI_NS)
        ET.register_namespace("dc", DC_NS)
        ET.register_namespace("dcterms", DCTERMS_NS)
        ET.register_namespace("rdf", RDF_NS)

        mets = ET.Element(
            f"{{{METS_NS}}}mets",
            {
                f"{{{XSI_NS}}}schemaLocation": f"{METS_NS} {METS_SCHEMA_URL}",
                "OBJID": resource_uri,
                "TYPE": "Arkumu Project Graph",
                "PROFILE": "arkumu-complete-graph-v1.0"
            }
        )

        # Add METS header
        mets_hdr = ET.SubElement(mets, f"{{{METS_NS}}}metsHdr", {
            "CREATEDATE": datetime.now(timezone.utc).isoformat(),
            "LASTMODDATE": datetime.now(timezone.utc).isoformat()
        })

        agent = ET.SubElement(mets_hdr, f"{{{METS_NS}}}agent", {
            "ROLE": "CREATOR",
            "TYPE": "OTHER",
            "OTHERTYPE": "SOFTWARE"
        })
        ET.SubElement(agent, f"{{{METS_NS}}}name").text = "Arkumu OAI-PMH Provider"
        ET.SubElement(agent, f"{{{METS_NS}}}note").text = "Generated by Arkumu Knowledge Graph System"

        return mets

    def _add_descriptive_metadata(self, mets: ET.Element, graph: Dict[str, Any]) -> None:
        """Add Dublin Core descriptive metadata section."""
        if not graph:
            return

        dmd_sec = ET.SubElement(mets, f"{{{METS_NS}}}dmdSec", {"ID": "DMD_001"})
        md_wrap = ET.SubElement(dmd_sec, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "DC",
            "MIMETYPE": "text/xml"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Build Dublin Core from graph
        dc_data = self._extract_dublin_core_from_graph(graph)

        # Create Dublin Core container
        dc_root = ET.SubElement(
            xml_data,
            f"{{{DC_NS}}}record",
            nsmap={
                "dc": DC_NS,
                "dcterms": DCTERMS_NS,
            },
        )

        for element, values in dc_data.items():
            if not values:
                continue
            prefix, term = element.split(":", 1)
            ns_uri = DC_NS if prefix == "dc" else DCTERMS_NS
            for value in values:
                if value is None:
                    continue
                ET.SubElement(dc_root, f"{{{ns_uri}}}{term}").text = value

    def _add_technical_metadata(self, mets: ET.Element, graph: Dict[str, Any], complete_graph: bool) -> None:
        """Add technical metadata about the graph."""
        tech_md = ET.SubElement(mets, f"{{{METS_NS}}}techMD", {"ID": "TECH_001"})
        md_wrap = ET.SubElement(tech_md, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "OTHER",
            "OTHERMDTYPE": "Arkumu Graph Metadata",
            "MIMETYPE": "application/json"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Technical metadata about the graph with safe handling of malformed data
        nodes = graph.get("nodes") or {}
        edges = graph.get("edges") or []

        tech_info = {
            "graph_type": "complete" if complete_graph else "direct",
            "entity_count": len(nodes) if isinstance(nodes, dict) else 0,
            "edge_count": len(edges) if isinstance(edges, list) else 0,
            "root_entity": graph.get("root_id"),
            "organization": self.org_code,
            "serialization_timestamp": datetime.now(timezone.utc).isoformat(),
            "format_version": "arkumu-graph-v1.0"
        }

        # Add as JSON
        tech_elem = ET.SubElement(xml_data, "technical_metadata")
        tech_elem.text = json.dumps(tech_info, indent=2)

    def _add_file_section(self, mets: ET.Element, graph: Dict[str, Any], resource_uri: str) -> None:
        """Add file section containing the complete graph data and content file locations."""
        file_sec = ET.SubElement(mets, f"{{{METS_NS}}}fileSec")
        file_grp = ET.SubElement(file_sec, f"{{{METS_NS}}}fileGrp", {"USE": "GRAPH_DATA"})

        # Add JSON-LD representation
        file_elem = ET.SubElement(file_grp, f"{{{METS_NS}}}file", {
            "ID": "GRAPH_JSONLD",
            "MIMETYPE": "application/ld+json",
            "USE": "GRAPH_SERIALIZATION"
        })

        # Embed the graph as JSON-LD
        f_content = ET.SubElement(file_elem, f"{{{METS_NS}}}FContent")
        xml_data = ET.SubElement(f_content, f"{{{METS_NS}}}xmlData")
        graph_elem = ET.SubElement(xml_data, "graph_data")
        graph_elem.text = json.dumps(graph, indent=2)

        # Add content files (if any) with presigned URLs suitable for Rosetta
        try:
            # Lazy imports to avoid hard dependency when storage is not configured
            from arkumu.metadata.models.resource import Resource
            from arkumu.storage.models.s3_file_objects import S3FileObject
            from arkumu.storage.services.rosetta_export_service import RosettaExportService

            resource = Resource.objects.filter(uri=resource_uri).first()
            if resource is None:
                return

            files_qs = (
                S3FileObject.objects.filter(related_resource=resource)
                .order_by("created_at")[:20]
            )
            if not files_qs:
                return

            content_grp = ET.SubElement(file_sec, f"{{{METS_NS}}}fileGrp", {"USE": "CONTENT"})
            export_svc = RosettaExportService()

            counter = 1
            for f in files_qs:
                attrs = {
                    "ID": f"FILE_{counter:04d}",
                    "MIMETYPE": getattr(f, "content_type", None) or "application/octet-stream",
                }
                if getattr(f, "file_size_bytes", None):
                    try:
                        attrs["SIZE"] = str(int(f.file_size_bytes))
                    except Exception:
                        pass
                # Rosetta profile forbids CHECKSUM attributes on mets:file; fixity stays in DNX metadata

                file_elem = ET.SubElement(content_grp, f"{{{METS_NS}}}file", attrs)

                # Build direct S3 URL without presigning
                url: Optional[str] = None
                try:
                    # Get bucket and organization
                    bucket = export_svc.bucket_name
                    s3_key = f.s3_key
                    endpoint = export_svc.endpoint_url

                    if endpoint and bucket and s3_key:
                        # Build direct URL: endpoint/bucket/key
                        url = f"{endpoint.rstrip('/')}/{bucket}/{s3_key}"
                except Exception:
                    url = None

                # Fallback to s3_url field if URL construction failed
                if not url and getattr(f, "s3_url", None):
                    url = f.s3_url

                if url:
                    href = _escape_flocat_href(url)
                    ET.SubElement(
                        file_elem,
                        f"{{{METS_NS}}}FLocat",
                        {
                            "LOCTYPE": "URL",
                            f"{{{XLINK_NS}}}href": href,
                        },
                    )

                counter += 1
        except Exception:
            # If storage is not configured or any error occurs, skip content files gracefully
            pass

    def _add_structural_map(self, mets: ET.Element, resource_uri: str) -> None:
        """Add logical structure map."""
        struct_map = ET.SubElement(mets, f"{{{METS_NS}}}structMap", {
            "TYPE": "logical",
            "LABEL": "Arkumu Project Graph Structure"
        })

        # Top-level div for the project
        div = ET.SubElement(struct_map, f"{{{METS_NS}}}div", {
            "TYPE": "project",
            "LABEL": f"Project: {resource_uri}",
            "DMDID": "DMD_001",
            "ADMID": "TECH_001"
        })

        # Link to the graph data with XLink attributes to ensure XLink namespace appears
        fptr = ET.SubElement(div, f"{{{METS_NS}}}fptr", {
            "FILEID": "GRAPH_JSONLD",
            f"{{{XLINK_NS}}}type": "simple"
        })

    def _extract_dublin_core_from_graph(self, graph: Dict[str, Any]) -> Dict[str, list]:
        """Extract Dublin Core elements from the graph."""
        from ..formats.dublin_core import DublinCoreSerializer, DEFAULT_PREDICATE_MAP
        import logging

        logger = logging.getLogger(__name__)
        print(f"[METS DEBUG] _extract_dublin_core_from_graph called: org={self.org_code}")
        logger.info(f"_extract_dublin_core_from_graph called: org={self.org_code}, root_id={graph.get('root_id')}, root_uri={graph.get('root_uri')}")

        root_id = graph.get("root_id")
        edges = graph.get("edges", [])

        # Get literal edges for the root entity
        def pred(e: Dict[str, Any]) -> str:
            return e.get("predicate_canonical") or e.get("predicate_uri")

        def obj_value(e: Dict[str, Any]) -> Optional[str]:
            return e.get("object_value")

        # Safe handling of edges in case it's None
        edges = edges or []
        root_literal_edges = [
            e for e in edges
            if e.get("subject_id") == root_id and e.get("object_value") is not None
        ]

        # Use the Dublin Core serializer
        serializer = DublinCoreSerializer(predicate_map=DEFAULT_PREDICATE_MAP)
        dc_data = serializer.serialize_from_triples(
            root_literal_edges,
            get_predicate=pred,
            get_object_value=obj_value
        )

        # Add creator/contributor from junction entities (actor-event relationships)
        creators, contributors = self._extract_creators_from_junctions(graph)
        if creators:
            dc_data.setdefault("dc:creator", []).extend(creators)
        if contributors:
            dc_data.setdefault("dc:contributor", []).extend(contributors)

        return dc_data

    def _extract_creators_from_junctions(self, graph: Dict[str, Any]) -> tuple[list, list]:
        """Extract creators and contributors from junction entities in the graph.

        Reads junctions directly from the graph edges/nodes structure - no database queries.

        Finds actor-event junction entities and extracts:
        - dc:creator: actors where ist-urheberin/besitzt-leistungsschutzrechte=1
        - dc:contributor: all other actors

        Format: "Actor Name (Role)" or just "Actor Name" if no role.
        """
        from arkumu.metadata.models.mappings import Mapping
        import logging

        logger = logging.getLogger(__name__)

        creators = []
        contributors = []

        edges = graph.get("edges", []) or []
        nodes = graph.get("nodes", {}) or {}

        if not edges or not nodes:
            return creators, contributors

        root_id = graph.get("root_id")
        root_uri = graph.get("root_uri")

        # Get schema property URIs for this organization
        actor_fk_uris = set()
        role_property_uris = set()
        copyright_flag_uris = set()
        junction_type_uris = set()

        if self.org_code:
            mapping = Mapping.get_active_for_organization(self.org_code)
            if mapping:
                schema = mapping.mapping_config.get('schema_manifest', {})
                for ds_name, ds_config in schema.items():
                    rel_contexts = ds_config.get('relationship_contexts', [])
                    if not rel_contexts:
                        continue

                    # Get junction type URI
                    entity_type = ds_config.get('entity_type', {})
                    type_uri = entity_type.get('uri', '')
                    if type_uri:
                        junction_type_uris.add(type_uri)

                    # Get actor FK URIs
                    fk_rels = ds_config.get('fk_relationships', [])
                    for rel in fk_rels:
                        target_ds = rel.get('target_dataset', '').lower()
                        if 'akteur' in target_ds or 'actor' in target_ds:
                            prop_uri = rel.get('source_property_uri', '')
                            if prop_uri:
                                actor_fk_uris.add(prop_uri)

                    # Get role URIs
                    for ctx in rel_contexts:
                        role_uri = ctx.get('context_property_uri', '')
                        if role_uri:
                            role_property_uris.add(role_uri)

                    # Get copyright flag URIs
                    properties = ds_config.get('properties', {})
                    for prop_name, prop_config in properties.items():
                        if 'urheber' in prop_name.lower() or 'leistungsschutz' in prop_name.lower():
                            flag_uri = prop_config.get('uri', '')
                            if flag_uri:
                                copyright_flag_uris.add(flag_uri)

        # Find junctions in the graph by type
        RDF_TYPE_URI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        junction_nodes = set()
        for edge in edges:
            pred_uri = edge.get("predicate_uri")
            obj_id = edge.get("object_id")
            if pred_uri == RDF_TYPE_URI and obj_id in junction_type_uris:
                junction_nodes.add(edge.get("subject_id"))

        if not junction_nodes:
            logger.debug(f"No junction nodes found in graph for types: {junction_type_uris}")
            return creators, contributors

        logger.debug(f"Found {len(junction_nodes)} junction nodes in graph")

        # Extract junction data from graph edges
        from collections import defaultdict
        junction_data = defaultdict(lambda: {"actor_id": None, "actor_name": None, "role": None, "is_copyright": False})

        for edge in edges:
            subj = edge.get("subject_id")
            if subj not in junction_nodes:
                continue

            pred_uri = edge.get("predicate_uri")
            obj_id = edge.get("object_id")
            obj_val = edge.get("object_value")

            # Extract actor FK
            if pred_uri in actor_fk_uris and obj_id:
                junction_data[subj]["actor_id"] = obj_id
                # Get actor name from nodes
                actor_node = nodes.get(obj_id, {})
                junction_data[subj]["actor_name"] = actor_node.get("name") or actor_node.get("uri", "").split("/")[-1]

            # Extract role
            elif pred_uri in role_property_uris and obj_val:
                junction_data[subj]["role"] = obj_val

            # Extract copyright flag
            elif pred_uri in copyright_flag_uris and obj_val:
                junction_data[subj]["is_copyright"] = obj_val in ("1", "true", True, 1)

        logger.debug(f"Extracted {len(junction_data)} junctions with actor/role data")

        # Institution keywords to filter out (these should be dc:publisher, not contributor)
        institution_keywords = [
            "universität", "hochschule", "akademie", "institut", "university",
            "college", "school", "academy", "institute", "stiftung", "foundation",
        ]

        def is_institution(name: str) -> bool:
            name_lower = name.lower()
            return any(kw in name_lower for kw in institution_keywords)

        # Build creator/contributor lists
        seen = set()
        for jdata in junction_data.values():
            actor_name = jdata.get("actor_name")
            if not actor_name or actor_name in seen:
                continue
            seen.add(actor_name)

            # Skip institutions - they should be dc:publisher, not creator/contributor
            if is_institution(actor_name):
                continue

            role = jdata.get("role")

            if role:
                formatted = f"{actor_name} ({role})"
            else:
                formatted = actor_name

            if jdata.get("is_copyright"):
                creators.append(formatted)
            else:
                contributors.append(formatted)

        logger.debug(f"Built {len(creators)} creators, {len(contributors)} contributors")
        return creators, contributors


__all__ = ["METSSerializer"]
