"""
METS (Metadata Encoding and Transmission Standard) serializer for complete project graphs.

This module packages complete project graphs from the Arkumu knowledge graph
into METS format, embedding the full graph as RDF/XML for semantic completeness.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Dict, Any, Optional

from lxml import etree as ET

from arkumu.metadata.services.canonical_graph_service import CanonicalGraphService


# METS namespaces
METS_NS = "http://www.loc.gov/METS/"
METS_SCHEMA_URL = "http://www.loc.gov/standards/mets/mets.xsd"
XLINK_NS = "http://www.w3.org/1999/xlink"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
DC_NS = "http://purl.org/dc/elements/1.1/"
DCTERMS_NS = "http://purl.org/dc/terms/"
RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"


def _escape_flocat_href(value: Optional[str]) -> Optional[str]:
    """Percent-encode square brackets for METS FLocat href values."""
    if not value:
        return value
    text = str(value)
    if not text:
        return text
    return text.replace('[', '%5B').replace(']', '%5D')


class METSSerializer:
    """
    METS serializer for complete project graphs.

    Packages complete project graphs as METS documents with:
    - Dublin Core descriptive metadata (dmdSec)
    - Technical metadata about the graph (techMD)
    - Complete graph as JSON-LD (dataStream)
    - Logical structure map (structMap)
    """

    def __init__(self, org_code: str, graph_service: Optional[CanonicalGraphService] = None):
        self.org_code = org_code
        self.graph_service = graph_service or CanonicalGraphService(org_code=org_code)

    def serialize_resource(self, resource_uri: str, include_complete_graph: bool = True) -> str:
        """
        Serialize a resource as METS with complete graph.

        Args:
            resource_uri: URI of the resource to serialize
            include_complete_graph: Whether to include the complete graph with all relationships

        Returns:
            XML string of the METS document
        """
        # Get the complete entity graph
        graph = self.graph_service.get_entity_graph(
            resource_uri,
            include_incoming=True,
            expand_neighbors=include_complete_graph
        )

        # Return empty string if no graph data or missing root_id
        if not graph or not graph.get("root_id"):
            return ""

        # Build METS document
        mets = self._build_mets_root(resource_uri)

        # Add descriptive metadata section
        self._add_descriptive_metadata(mets, graph)

        # Add technical metadata section
        self._add_technical_metadata(mets, graph, include_complete_graph)

        # Add file section with graph data and content locations
        self._add_file_section(mets, graph, resource_uri)

        # Add structural map
        self._add_structural_map(mets, resource_uri)

        # Convert to string
        return ET.tostring(mets, encoding='utf-8', xml_declaration=True).decode('utf-8')

    def _build_mets_root(self, resource_uri: str) -> ET.Element:
        """Build the root METS element with namespaces."""
        # Register namespaces to control prefixes and avoid duplicates
        ET.register_namespace("mets", METS_NS)
        ET.register_namespace("xlink", XLINK_NS)
        ET.register_namespace("xsi", XSI_NS)
        ET.register_namespace("dc", DC_NS)
        ET.register_namespace("dcterms", DCTERMS_NS)
        ET.register_namespace("rdf", RDF_NS)

        mets = ET.Element(
            f"{{{METS_NS}}}mets",
            {
                f"{{{XSI_NS}}}schemaLocation": f"{METS_NS} {METS_SCHEMA_URL}",
                "OBJID": resource_uri,
                "TYPE": "Arkumu Project Graph",
                "PROFILE": "arkumu-complete-graph-v1.0"
            }
        )

        # Add METS header
        mets_hdr = ET.SubElement(mets, f"{{{METS_NS}}}metsHdr", {
            "CREATEDATE": datetime.now(timezone.utc).isoformat(),
            "LASTMODDATE": datetime.now(timezone.utc).isoformat()
        })

        agent = ET.SubElement(mets_hdr, f"{{{METS_NS}}}agent", {
            "ROLE": "CREATOR",
            "TYPE": "OTHER",
            "OTHERTYPE": "SOFTWARE"
        })
        ET.SubElement(agent, f"{{{METS_NS}}}name").text = "Arkumu OAI-PMH Provider"
        ET.SubElement(agent, f"{{{METS_NS}}}note").text = "Generated by Arkumu Knowledge Graph System"

        return mets

    def _add_descriptive_metadata(self, mets: ET.Element, graph: Dict[str, Any]) -> None:
        """Add Dublin Core descriptive metadata section."""
        if not graph:
            return

        dmd_sec = ET.SubElement(mets, f"{{{METS_NS}}}dmdSec", {"ID": "DMD_001"})
        md_wrap = ET.SubElement(dmd_sec, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "DC",
            "MIMETYPE": "text/xml"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Build Dublin Core from graph
        dc_data = self._extract_dublin_core_from_graph(graph)

        # Create Dublin Core container
        dc_root = ET.SubElement(
            xml_data,
            f"{{{DC_NS}}}record",
            nsmap={
                "dc": DC_NS,
                "dcterms": DCTERMS_NS,
            },
        )

        for element, values in dc_data.items():
            if not values:
                continue
            prefix, term = element.split(":", 1)
            ns_uri = DC_NS if prefix == "dc" else DCTERMS_NS
            for value in values:
                if value is None:
                    continue
                ET.SubElement(dc_root, f"{{{ns_uri}}}{term}").text = value

    def _add_technical_metadata(self, mets: ET.Element, graph: Dict[str, Any], complete_graph: bool) -> None:
        """Add technical metadata about the graph."""
        tech_md = ET.SubElement(mets, f"{{{METS_NS}}}techMD", {"ID": "TECH_001"})
        md_wrap = ET.SubElement(tech_md, f"{{{METS_NS}}}mdWrap", {
            "MDTYPE": "OTHER",
            "OTHERMDTYPE": "Arkumu Graph Metadata",
            "MIMETYPE": "application/json"
        })
        xml_data = ET.SubElement(md_wrap, f"{{{METS_NS}}}xmlData")

        # Technical metadata about the graph with safe handling of malformed data
        nodes = graph.get("nodes") or {}
        edges = graph.get("edges") or []

        tech_info = {
            "graph_type": "complete" if complete_graph else "direct",
            "entity_count": len(nodes) if isinstance(nodes, dict) else 0,
            "edge_count": len(edges) if isinstance(edges, list) else 0,
            "root_entity": graph.get("root_id"),
            "organization": self.org_code,
            "serialization_timestamp": datetime.now(timezone.utc).isoformat(),
            "format_version": "arkumu-graph-v1.0"
        }

        # Add as JSON
        tech_elem = ET.SubElement(xml_data, "technical_metadata")
        tech_elem.text = json.dumps(tech_info, indent=2)

    def _add_file_section(self, mets: ET.Element, graph: Dict[str, Any], resource_uri: str) -> None:
        """Add file section containing the complete graph data and content file locations."""
        file_sec = ET.SubElement(mets, f"{{{METS_NS}}}fileSec")
        file_grp = ET.SubElement(file_sec, f"{{{METS_NS}}}fileGrp", {"USE": "GRAPH_DATA"})

        # Add JSON-LD representation
        file_elem = ET.SubElement(file_grp, f"{{{METS_NS}}}file", {
            "ID": "GRAPH_JSONLD",
            "MIMETYPE": "application/ld+json",
            "USE": "GRAPH_SERIALIZATION"
        })

        # Embed the graph as JSON-LD
        f_content = ET.SubElement(file_elem, f"{{{METS_NS}}}FContent")
        xml_data = ET.SubElement(f_content, f"{{{METS_NS}}}xmlData")
        graph_elem = ET.SubElement(xml_data, "graph_data")
        graph_elem.text = json.dumps(graph, indent=2)

        # Add content files (if any) with presigned URLs suitable for Rosetta
        try:
            # Lazy imports to avoid hard dependency when storage is not configured
            from arkumu.metadata.models.resource import Resource
            from arkumu.storage.models.s3_file_objects import S3FileObject
            from arkumu.storage.services.rosetta_export_service import RosettaExportService

            resource = Resource.objects.filter(uri=resource_uri).first()
            if resource is None:
                return

            files_qs = (
                S3FileObject.objects.filter(related_resource=resource)
                .order_by("created_at")[:20]
            )
            if not files_qs:
                return

            content_grp = ET.SubElement(file_sec, f"{{{METS_NS}}}fileGrp", {"USE": "CONTENT"})
            export_svc = RosettaExportService()

            counter = 1
            for f in files_qs:
                attrs = {
                    "ID": f"FILE_{counter:04d}",
                    "MIMETYPE": getattr(f, "content_type", None) or "application/octet-stream",
                }
                if getattr(f, "file_size_bytes", None):
                    try:
                        attrs["SIZE"] = str(int(f.file_size_bytes))
                    except Exception:
                        pass
                # Rosetta profile forbids CHECKSUM attributes on mets:file; fixity stays in DNX metadata

                file_elem = ET.SubElement(content_grp, f"{{{METS_NS}}}file", attrs)

                # Build direct S3 URL without presigning
                url: Optional[str] = None
                try:
                    # Get bucket and organization
                    bucket = export_svc.bucket_name
                    s3_key = f.s3_key
                    endpoint = export_svc.endpoint_url

                    if endpoint and bucket and s3_key:
                        # Build direct URL: endpoint/bucket/key
                        url = f"{endpoint.rstrip('/')}/{bucket}/{s3_key}"
                except Exception:
                    url = None

                # Fallback to s3_url field if URL construction failed
                if not url and getattr(f, "s3_url", None):
                    url = f.s3_url

                if url:
                    href = _escape_flocat_href(url)
                    ET.SubElement(
                        file_elem,
                        f"{{{METS_NS}}}FLocat",
                        {
                            "LOCTYPE": "URL",
                            f"{{{XLINK_NS}}}href": href,
                        },
                    )

                counter += 1
        except Exception:
            # If storage is not configured or any error occurs, skip content files gracefully
            pass

    def _add_structural_map(self, mets: ET.Element, resource_uri: str) -> None:
        """Add logical structure map."""
        struct_map = ET.SubElement(mets, f"{{{METS_NS}}}structMap", {
            "TYPE": "logical",
            "LABEL": "Arkumu Project Graph Structure"
        })

        # Top-level div for the project
        div = ET.SubElement(struct_map, f"{{{METS_NS}}}div", {
            "TYPE": "project",
            "LABEL": f"Project: {resource_uri}",
            "DMDID": "DMD_001",
            "ADMID": "TECH_001"
        })

        # Link to the graph data with XLink attributes to ensure XLink namespace appears
        fptr = ET.SubElement(div, f"{{{METS_NS}}}fptr", {
            "FILEID": "GRAPH_JSONLD",
            f"{{{XLINK_NS}}}type": "simple"
        })

    def _extract_dublin_core_from_graph(self, graph: Dict[str, Any]) -> Dict[str, list]:
        """Extract Dublin Core elements from the graph."""
        from ..formats.dublin_core import DublinCoreSerializer, DEFAULT_PREDICATE_MAP

        root_id = graph.get("root_id")
        edges = graph.get("edges", [])

        # Get literal edges for the root entity
        def pred(e: Dict[str, Any]) -> str:
            return e.get("predicate_canonical") or e.get("predicate_uri")

        def obj_value(e: Dict[str, Any]) -> Optional[str]:
            return e.get("object_value")

        # Safe handling of edges in case it's None
        edges = edges or []
        root_literal_edges = [
            e for e in edges
            if e.get("subject_id") == root_id and e.get("object_value") is not None
        ]

        # Use the Dublin Core serializer
        serializer = DublinCoreSerializer(predicate_map=DEFAULT_PREDICATE_MAP)
        dc_data = serializer.serialize_from_triples(
            root_literal_edges,
            get_predicate=pred,
            get_object_value=obj_value
        )

        # Add creator/contributor from junction entities (actor-event relationships)
        creators, contributors = self._extract_creators_from_junctions(graph)
        if creators:
            dc_data.setdefault("dc:creator", []).extend(creators)
        if contributors:
            dc_data.setdefault("dc:contributor", []).extend(contributors)

        return dc_data

    def _extract_creators_from_junctions(self, graph: Dict[str, Any]) -> tuple[list, list]:
        """Extract creators and contributors from junction entities.

        Finds actor-event junction entities in the graph and extracts:
        - dc:creator: actors where ist-urheberin=1 (copyright holders)
        - dc:contributor: actors where ist-urheberin=0

        Format: "Actor Name (Role)" or just "Actor Name" if no role.
        """
        from arkumu.metadata.models.triples import Triple
        from arkumu.metadata.canonical import canonical_uri
        from django.db.models import Q
        import uuid

        creators = []
        contributors = []

        # Get root identifier - try root_id first, fallback to root_uri
        root_id = graph.get("root_id")
        root_uri = graph.get("root_uri") if not root_id else None

        # For URI-based graphs (from get_project_graphs), resolve URI to UUID
        if root_uri and not root_id:
            try:
                from arkumu.metadata.models.resource import Resource
                root_resource = Resource.objects.filter(uri=root_uri).only("id").first()
                if root_resource:
                    root_id = str(root_resource.id)
                else:
                    return creators, contributors
            except Exception:
                return creators, contributors

        if not root_id:
            return creators, contributors

        edges = graph.get("edges", []) or []
        nodes = graph.get("nodes", {}) or {}

        # Find direct event IDs using canonical event predicate (org-agnostic)
        EVENT_CANONICAL = canonical_uri("event")
        event_ids = set()
        for edge in edges:
            subj = edge.get("subject_id")
            pred_canonical = edge.get("predicate_canonical")
            obj = edge.get("object_id")
            if subj == root_id and pred_canonical == EVENT_CANONICAL and obj:
                event_ids.add(obj)

        if not event_ids:
            return creators, contributors

        # Convert URIs to UUIDs if necessary (for URI-based graphs)
        if event_ids and "http" in str(next(iter(event_ids))):
            from arkumu.metadata.models.resource import Resource
            event_resources = Resource.objects.filter(uri__in=event_ids).only("id")
            valid_event_ids = [str(r.id) for r in event_resources]
        else:
            # Validate that event_ids are valid UUIDs (skip if mock data)
            valid_event_ids = []
            for eid in event_ids:
                try:
                    uuid.UUID(str(eid))
                    valid_event_ids.append(eid)
                except (ValueError, AttributeError):
                    pass

        if not valid_event_ids:
            return creators, contributors

        # Query junction entities that point to these events using schema manifest
        from arkumu.metadata.models.resource import Resource
        from arkumu.metadata.models.mappings import Mapping

        RDF_TYPE_URI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"

        # Get junction dataset types from schema manifest
        junction_type_uris = []
        if self.org_code:
            mapping = Mapping.get_active_for_organization(self.org_code)
            if mapping:
                schema = mapping.mapping_config.get('schema_manifest', {})
                for ds_name, ds_config in schema.items():
                    # Check if this dataset has relationship_contexts (junction indicator)
                    rel_contexts = ds_config.get('relationship_contexts', [])
                    if rel_contexts:
                        # Get the type URI for this junction dataset
                        entity_type = ds_config.get('entity_type', {})
                        dataset_type_uri = entity_type.get('uri', '')
                        if dataset_type_uri:
                            junction_type_uris.append(dataset_type_uri)

        if not junction_type_uris:
            # Fallback to canonical junction types if schema not available
            junction_type_uris = [
                "http://arkumu.org/data/types/akteurin-ereignis-kreuztabelle",
                "http://arkumu.org/data/types/akteurin-akteurin-kreuztabelle",
            ]

        org_filter = Q()
        if self.org_code:
            org_filter = Q(subject__organization__code=self.org_code)

        try:
            junction_type_subjects = list(
                Triple.objects.filter(
                    Q(predicate__uri=RDF_TYPE_URI)
                    & (
                        Q(object__canonical_uri__in=junction_type_uris)
                        | Q(object__uri__in=junction_type_uris)
                    )
                )
                .filter(org_filter)
                .values_list("subject_id", flat=True)
            )

            # Find junctions pointing to our events
            junction_ids = list(
                Triple.objects.filter(
                    subject_id__in=junction_type_subjects,
                    object_id__in=valid_event_ids,
                )
                .values_list("subject_id", flat=True)
                .distinct()[:50]  # Limit to avoid performance issues
            )
        except Exception:
            # Handle mock data or DB errors gracefully
            return creators, contributors

        if not junction_ids:
            return creators, contributors

        # Fetch junction triples
        junction_triples = Triple.objects.filter(
            subject_id__in=junction_ids
        ).select_related("predicate", "object").only(
            "subject_id",
            "predicate__uri",
            "predicate__canonical_uri",
            "object__id",
            "object__uri",
            "object__value",
            "object__name",
        )

        # Canonical URIs for junction properties
        ACTOR_IN_EVENT_CANONICAL = canonical_uri("actor_in_event")
        ROLE_IN_EVENT_CANONICAL = canonical_uri("role_in_event")
        IST_URHEBERIN_CANONICAL = "http://arkumu.org/data/properties/ist-urheberin"

        # Group by junction entity
        junction_data: Dict[str, Dict[str, Any]] = {}
        for t in junction_triples:
            jid = str(t.subject_id)
            if jid not in junction_data:
                junction_data[jid] = {"ist_urheberin": False, "actor_id": None, "role": None}

            pred_canonical = t.predicate.canonical_uri or ""
            pred_uri = t.predicate.uri or ""

            # Check canonical URI first, fallback to substring matching for legacy support
            if pred_canonical == IST_URHEBERIN_CANONICAL or "ist-urheberin" in pred_uri:
                val = t.object.value if hasattr(t.object, "value") else None
                junction_data[jid]["ist_urheberin"] = val in ("1", "true", True, 1)
            elif pred_canonical == ACTOR_IN_EVENT_CANONICAL or "akteurin-im-ereignis" in pred_uri or "akteurin" in pred_uri.split("/")[-1]:
                junction_data[jid]["actor_id"] = str(t.object.id)
            elif pred_canonical == ROLE_IN_EVENT_CANONICAL or "rollen-der-akteurin" in pred_uri or "rolle" in pred_uri.split("/")[-1]:
                # Get role name
                role_val = t.object.value or t.object.name if hasattr(t.object, "value") else None
                if role_val:
                    junction_data[jid]["role"] = role_val

        # Fetch actor names
        actor_ids = [d["actor_id"] for d in junction_data.values() if d.get("actor_id")]
        actor_names = {}
        if actor_ids:
            for res in Resource.objects.filter(id__in=actor_ids).only("id", "name", "uri"):
                actor_names[str(res.id)] = res.name or res.uri.split("/")[-1]

        # Institution keywords to filter out (these should be dc:publisher, not contributor)
        institution_keywords = [
            "universität", "hochschule", "akademie", "institut", "university",
            "college", "school", "academy", "institute", "stiftung", "foundation",
        ]

        def is_institution(name: str) -> bool:
            name_lower = name.lower()
            return any(kw in name_lower for kw in institution_keywords)

        # Build creator/contributor lists
        seen = set()
        for jdata in junction_data.values():
            actor_id = jdata.get("actor_id")
            if not actor_id or actor_id in seen:
                continue
            seen.add(actor_id)

            actor_name = actor_names.get(actor_id, "Unknown")

            # Skip institutions - they should be dc:publisher, not creator/contributor
            if is_institution(actor_name):
                continue

            role = jdata.get("role")

            if role:
                formatted = f"{actor_name} ({role})"
            else:
                formatted = actor_name

            if jdata.get("ist_urheberin"):
                creators.append(formatted)
            else:
                contributors.append(formatted)

        return creators, contributors


__all__ = ["METSSerializer"]
