# Generated by Django 5.0.11 on 2025-08-01 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumableUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_size_bytes', models.BigIntegerField()),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('chunk_size_bytes', models.IntegerField(default=5242880)),
                ('total_chunks', models.IntegerField()),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('uploading', 'Uploading'), ('paused', 'Paused'), ('assembling', 'Assembling Chunks'), ('completed', 'Completed'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_chunk_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('temp_storage_path', models.CharField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('s3_file_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumable_upload', to='storage.s3fileobject')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumable_uploads', to='storage.uploadsession')),
            ],
            options={
                'verbose_name': 'Resumable Upload Session',
                'verbose_name_plural': 'Resumable Upload Sessions',
            },
        ),
        migrations.CreateModel(
            name='ResumableUploadChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_number', models.IntegerField()),
                ('start_byte', models.BigIntegerField()),
                ('end_byte', models.BigIntegerField()),
                ('size_bytes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('temp_file_path', models.CharField(blank=True, max_length=512)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('resumable_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage.resumableuploadsession')),
            ],
            options={
                'verbose_name': 'Resumable Upload Chunk',
                'verbose_name_plural': 'Resumable Upload Chunks',
                'ordering': ['chunk_number'],
            },
        ),
        migrations.AddIndex(
            model_name='resumableuploadsession',
            index=models.Index(fields=['upload_session'], name='storage_res_upload__99bcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadsession',
            index=models.Index(fields=['status'], name='storage_res_status_9bbc03_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadsession',
            index=models.Index(fields=['created_at'], name='storage_res_created_223a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadsession',
            index=models.Index(fields=['last_chunk_uploaded_at'], name='storage_res_last_ch_39e388_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadchunk',
            index=models.Index(fields=['resumable_upload', 'chunk_number'], name='storage_res_resumab_5d8c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadchunk',
            index=models.Index(fields=['status'], name='storage_res_status_357211_idx'),
        ),
        migrations.AddIndex(
            model_name='resumableuploadchunk',
            index=models.Index(fields=['created_at'], name='storage_res_created_82c4c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumableuploadchunk',
            unique_together={('resumable_upload', 'chunk_number')},
        ),
    ]
