# Generated by Django 5.0.11 on 2025-08-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_resumableuploadsession_resumableuploadchunk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumableuploadchunk',
            name='temp_file_path',
        ),
        migrations.RemoveField(
            model_name='resumableuploadsession',
            name='temp_storage_path',
        ),
    ]
