# Generated by Django 5.0.11 on 2025-09-01 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_temp_file_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=255)),
                ('base_folder', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('presigned_generated', 'Presigned URLs Generated'), ('uploading', 'Uploading to S3'), ('processing', 'Processing Files'), ('completed', 'Completed'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('completed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_async_upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsyncUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('relative_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading to S3'), ('uploaded', 'Uploaded to S3'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('presigned_url', models.TextField()),
                ('presigned_fields', models.JSONField(default=dict)),
                ('upload_started_at', models.DateTimeField(blank=True, null=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_file_object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.s3fileobject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.asyncuploadsession')),
            ],
            options={
                'db_table': 'storage_async_upload_file',
                'ordering': ['created_at'],
            },
        ),
    ]
