# Generated by Django 5.0.11 on 2025-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_asyncuploadsession_asyncuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3fileobject',
            name='checksum_calculated_at',
            field=models.DateTimeField(blank=True, help_text='When the checksum was calculated', null=True),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='sha256_checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum of the file content', max_length=64),
        ),
    ]
