# Generated by Django 5.0.11 on 2025-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_s3fileobject_checksum_calculated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncuploadsession',
            name='status',
            field=models.CharField(
                choices=[
                    ('initialized', 'Initialized'),
                    ('presigned_generated', 'Presigned URLs Generated'),
                    ('uploading', 'Uploading to S3'),
                    ('awaiting_verification', 'Awaiting verification'),
                    ('processing', 'Processing Files'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                default='initialized',
                max_length=32,
            ),
        ),
    ]

