# Generated by Django 5.0.11 on 2025-10-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_asyncuploadsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3fileobject',
            name='base_folder',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='s3fileobject',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['base_folder'], name='storage_s3_base_79f6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['organization'], name='storage_s3_organi_df69c9_idx'),
        ),
    ]

