# Generated by Django 5.0.11 on 2025-10-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_s3fileobject_org_base_folder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='s3fileobject',
            new_name='storage_s3f_base_fo_e4881b_idx',
            old_name='storage_s3_base_79f6c3_idx',
        ),
        migrations.RenameIndex(
            model_name='s3fileobject',
            new_name='storage_s3f_organiz_d30249_idx',
            old_name='storage_s3_organi_df69c9_idx',
        ),
    ]
