# Generated by Django 5.0.11 on 2025-11-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_add_s3fileobject_related_name'),
        ('storage', '0009_rename_storage_s3_base_79f6c3_idx_storage_s3f_base_fo_e4881b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3fileobject',
            name='related_resource',
            field=models.ForeignKey(blank=True, help_text='Direct link to the metadata resource this file is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3fileobject', to='metadata.resource'),
        ),
        migrations.AlterField(
            model_name='s3fileobject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('missing', 'Missing'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
