# Generated by Django 5.0.11 on 2025-07-30 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_add_harmonization_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='harmonizationconflict',
            new_name='metadata_ha_executi_768405_idx',
            old_name='metadata_ha_executi_c14502_idx',
        ),
        migrations.RenameIndex(
            model_name='harmonizationconflict',
            new_name='metadata_ha_source__8158fe_idx',
            old_name='metadata_ha_source__0b3fcc_idx',
        ),
        migrations.RenameIndex(
            model_name='harmonizationexecution',
            new_name='metadata_ha_status_e22fb6_idx',
            old_name='metadata_ha_status_fb96f1_idx',
        ),
        migrations.RenameIndex(
            model_name='harmonizationexecution',
            new_name='metadata_ha_complet_8ab6fb_idx',
            old_name='metadata_ha_complet_d5848f_idx',
        ),
        migrations.RenameIndex(
            model_name='harmonizationrule',
            new_name='metadata_ha_source__d011e7_idx',
            old_name='metadata_ha_source__a3b5d2_idx',
        ),
        migrations.RenameIndex(
            model_name='harmonizationrule',
            new_name='metadata_ha_catalog_f8ccef_idx',
            old_name='metadata_ha_catalog_e25fda_idx',
        ),
        migrations.AlterField(
            model_name='harmonizationconflict',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='harmonizationexecution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='harmonizationrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
