# Generated by Django 5.0.11 on 2025-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_rename_metadata_ha_executi_c14502_idx_metadata_ha_executi_768405_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='public_access_level',
            field=models.CharField(choices=[('private', 'Private - Organization only'), ('restricted', 'Restricted - Authenticated users only'), ('public', 'Public - Catalog display allowed')], default='restricted', help_text='Level of public access for this resource', max_length=20),
        ),
    ]
