# Generated by Django 5.0.11 on 2025-09-11 09:41

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_resource_public_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogView',
            fields=[
                ('unified_uri', models.URLField(max_length=512, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Main title from any archive')),
                ('alternative_titles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='All alternative titles across archives', size=None)),
                ('creators', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='All creators/actors across archives', size=None)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, help_text='All relevant dates', size=None)),
                ('source_archives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='Archives that have this resource', size=None)),
                ('oai_metadata', models.JSONField(default=dict, help_text='Pre-computed OAI-PMH metadata')),
                ('triple_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='harmonizationexecution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='harmonizationexecution',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='harmonizationexecution',
            name='rules_applied',
        ),
        migrations.RemoveField(
            model_name='harmonizationexecution',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='harmonizationrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='harmonizationrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='harmonizationrule',
            name='source_organization',
        ),
        migrations.RemoveField(
            model_name='harmonizationrule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='harmonizationrule',
            name='validated_by',
        ),
        migrations.CreateModel(
            name='HarmonizationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_uri', models.URLField(db_index=True, help_text='Archive-specific URI (e.g., http://arkumu.org/data/rsh/types/akteurin)', max_length=512)),
                ('target_uri', models.URLField(db_index=True, help_text='Unified model URI (e.g., http://arkumu.org/types/akteurin)', max_length=512)),
                ('mapping_type', models.CharField(choices=[('automatic', 'Automatic (pattern-based)'), ('explicit', 'Explicit (CSV-defined)'), ('derived', 'Derived (computed)')], default='explicit', max_length=20)),
                ('resource_type', models.CharField(choices=[('IRI', 'IRI Identified Resource'), ('CLASS', 'Class'), ('PROPERTY', 'Property'), ('LITERAL', 'Literal')], help_text='Type of resource being mapped (Class, Property, etc.)', max_length=10)),
                ('label', models.CharField(blank=True, help_text='Human-readable label for the unified concept', max_length=255)),
                ('archive_labels', models.JSONField(default=dict, help_text="Archive-specific labels/identifiers, e.g., {'hmt': '04_hfm_Akteurin,06_hfm_Koerperschaften'}")),
                ('source_archive', models.CharField(db_index=True, help_text="Archive identifier (e.g., 'rsh', 'hmt', 'fuk')", max_length=50)),
                ('is_catalog_visible', models.BooleanField(default=True, help_text='Whether this mapping appears in the public catalog')),
                ('catalog_priority', models.IntegerField(default=100, help_text='Display priority in catalog (lower = higher priority)')),
                ('oai_pmh_element', models.CharField(blank=True, help_text="Dublin Core element for OAI-PMH (e.g., 'dc:title', 'dc:creator')", max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HarmonizationConflict',
        ),
        migrations.DeleteModel(
            name='HarmonizationExecution',
        ),
        migrations.DeleteModel(
            name='HarmonizationRule',
        ),
        migrations.AddIndex(
            model_name='harmonizationmapping',
            index=models.Index(fields=['source_uri', 'resource_type'], name='metadata_ha_source__ce45cc_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationmapping',
            index=models.Index(fields=['target_uri', 'resource_type'], name='metadata_ha_target__d18f91_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationmapping',
            index=models.Index(fields=['source_archive', 'is_catalog_visible'], name='metadata_ha_source__f5a108_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationmapping',
            index=models.Index(fields=['catalog_priority', 'is_catalog_visible'], name='metadata_ha_catalog_de6da9_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationmapping',
            index=models.Index(fields=['source_uri'], name='source_uri_pattern_idx', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='harmonizationmapping',
            unique_together={('source_uri', 'target_uri', 'source_archive')},
        ),
    ]
