# Generated by Django 5.0.11 on 2025-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_create_harmonization_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='canonical_uri',
            field=models.URLField(blank=True, db_index=True, help_text='Unified catalog URI this resource maps to for cross-archive harmonization', max_length=512, null=True),
        ),
    ]
