# Generated by Django 5.0.11 on 2025-09-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_add_canonical_uri_to_resource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harmonizationmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='harmonizationmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='harmonizationmapping',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CatalogView',
        ),
        migrations.DeleteModel(
            name='HarmonizationMapping',
        ),
    ]
