# Generated by Django 5.0.11 on 2025-09-21 16:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_alter_harmonizationmapping_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('IRI', 'IRI Identified Resource'), ('ENTITY', 'Entity'), ('CLASS', 'Class'), ('PROPERTY', 'Property'), ('LITERAL', 'Literal')], default='IRI', help_text='Type of the resource (IRI, Class, Property, or Literal)', max_length=10),
        ),
        migrations.CreateModel(
            name='WikidataEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wikidata_id', models.CharField(help_text='Wikidata identifier (e.g. Q42)', max_length=32, unique=True)),
                ('label_de', models.CharField(blank=True, help_text='Preferred German label', max_length=255)),
                ('label_en', models.CharField(blank=True, help_text='Preferred English label', max_length=255)),
                ('description_de', models.TextField(blank=True, help_text='German description')),
                ('aliases_de', models.JSONField(blank=True, default=list, help_text='List of German aliases provided by Wikidata')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw Wikidata entity payload used for debugging')),
                ('last_resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when this entity was last refreshed from Wikidata', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['wikidata_id'],
                'indexes': [models.Index(fields=['wikidata_id'], name='metadata_wi_wikidat_980a04_idx')],
            },
        ),
    ]
