# Generated by Django 5.0.11 on 2025-09-23 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_resource_resource_type_wikidataentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSourcesEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_id', models.CharField(help_text='Identifier (e.g. Q42)', max_length=32)),
                ('property', models.CharField(help_text='Property', max_length=255)),
                ('datum', models.CharField(default=dict, help_text='Datum retrieved from Source')),
                ('source', models.CharField(choices=[('WD', 'WikiData')], help_text='DataSource', max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_id'],
            },
        ),
        migrations.DeleteModel(
            name='WikidataEntity',
        ),
        migrations.AddIndex(
            model_name='externalsourcesentity',
            index=models.Index(fields=['data_id'], name='metadata_ex_data_id_e14d25_idx'),
        ),
    ]
