# Generated by Django 5.0.11 on 2025-11-07 08:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_resource_resource_type_wikidataentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSelectionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('mapping_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('set', 'Set Active'), ('cleared', 'Cleared')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_audits', to='metadata.mapping')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_selection_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapping Selection Audit',
                'verbose_name_plural': 'Mapping Selection Audits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization_id', '-timestamp'], name='metadata_ma_organiz_4b2fad_idx'), models.Index(fields=['user', '-timestamp'], name='metadata_ma_user_id_41deed_idx'), models.Index(fields=['-timestamp'], name='metadata_ma_timesta_602211_idx')],
            },
        ),
    ]
