# Generated by Django 5.0.11 on 2025-09-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_externalsourcesentity_delete_wikidataentity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalsourcesentity',
            options={'ordering': ['source', 'data_id', 'property'], 'verbose_name': 'External Entity', 'verbose_name_plural': 'External Entities'},
        ),
        migrations.AlterUniqueTogether(
            name='externalsourcesentity',
            unique_together={('source', 'data_id', 'property')},
        ),
    ]
