# Generated by Django 5.0.11 on 2025-11-07 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_add_mapping_selection_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this is the active mapping for this organization'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['organization_id', 'is_active'], name='metadata_ma_organiz_a16cbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization_id',), name='unique_active_mapping_per_org'),
        ),
    ]
