# Generated by Django 5.0.11 on 2025-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_alter_externalsourcesentity_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalsourcesentity',
            unique_together=set(),
        ),
    ]
