# Generated by Django 5.0.11 on 2025-11-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_add_is_active_to_mapping'),
        ('metadata', '0013_alter_externalsourcesentity_unique_together'),
    ]

    operations = [
    ]
