# Generated by Django 5.0.11 on 2025-11-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_mappingforeignkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MappingForeignKey',
        ),
    ]
