"""Auto-generated from schema manifest."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class C00HfmProjekte:
    """Dataset 00_hfm_Projekte (canonical http://arkumu.org/data/hmt/types/00-hfm-projekte)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    besetzung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Besetzung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/besetzung', 'local_uri': 'http://arkumu.org/data/hmt/properties/besetzung' })
    gnd_nummer: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'GND-Nummer', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/gnd-nummer', 'local_uri': 'http://arkumu.org/data/hmt/properties/gnd-nummer' })
    hfmt_werk_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Werk_ID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id' })
    projekt_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_Sprache', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/projekt-sprache', 'local_uri': 'http://arkumu.org/data/hmt/properties/projekt-sprache' })
    projektart_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projektart_calc', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/projektart-calc', 'local_uri': 'http://arkumu.org/data/hmt/properties/projektart-calc' })
    projektkategorie: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projektkategorie', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/projektkategorie', 'local_uri': 'http://arkumu.org/data/hmt/properties/projektkategorie' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    bevorzugter_titel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bevorzugter Titel', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-titel', 'local_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-titel' })
    alternativer_titel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Alternativer Titel', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/alternativer-titel', 'local_uri': 'http://arkumu.org/data/hmt/properties/alternativer-titel' })
    interner_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Interner Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar' })
    id_karsten_oberwerk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'ID_Karsten_Oberwerk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/id-karsten-oberwerk', 'local_uri': 'http://arkumu.org/data/hmt/properties/id-karsten-oberwerk' })
    organisationseinheit: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Organisationseinheit', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/organisationseinheit', 'local_uri': 'http://arkumu.org/data/hmt/properties/organisationseinheit' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    ist_teil_von_oberwerk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'ist_Teil_von_Oberwerk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ist-teil-von-oberwerk', 'local_uri': 'http://arkumu.org/data/hmt/properties/ist-teil-von-oberwerk' })
    bevorzugter_untertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bevorzugter Untertitel', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-untertitel', 'local_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-untertitel' })
    einliefernde_hochschule: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Einliefernde Hochschule', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/einliefernde-hochschule', 'local_uri': 'http://arkumu.org/data/hmt/properties/einliefernde-hochschule' })
    bevorzugter_titel_sprachauszeichnung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bevorzugter Titel Sprachauszeichnung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-titel-sprachauszeichnung', 'local_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-titel-sprachauszeichnung' })
    exportvariablen_arkumu_rechtsstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Rechtsstatus', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-rechtsstatus', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-rechtsstatus' })
    alternativer_titel_sprachauszeichnung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Alternativer Titel Sprachauszeichnung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/alternativer-titel-sprachauszeichnung', 'local_uri': 'http://arkumu.org/data/hmt/properties/alternativer-titel-sprachauszeichnung' })
    bevorzugter_untertitel_sprachauszeichnung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bevorzugter Untertitel Sprachauszeichnung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-untertitel-sprachauszeichnung', 'local_uri': 'http://arkumu.org/data/hmt/properties/bevorzugter-untertitel-sprachauszeichnung' })
    projekte_exportinfos_projektkategorien_arkumu: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Exportinfos_Projektkategorien_arkumu', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/projekte-exportinfos-projektkategorien-arkumu', 'local_uri': 'http://arkumu.org/data/hmt/properties/projekte-exportinfos-projektkategorien-arkumu' })
    exportvariablen_arkumu_art_des_lizenzvertrages: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Art des Lizenzvertrages', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-art-des-lizenzvertrages', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-art-des-lizenzvertrages' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })
    exportvariablen_arkumu_bestehender_lizenzvertrag: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Bestehender Lizenzvertrag', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-bestehender-lizenzvertrag', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-bestehender-lizenzvertrag' })

@dataclass
class C02HfmEreignis:
    """Dataset 02_hfm_Ereignis (canonical http://arkumu.org/data/hmt/types/02-hfm-ereignis)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    ereignisnr: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisNr', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisnr', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisnr' })
    ereignistyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignistyp', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignistyp', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignistyp' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    ereignisbeschreibung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisBeschreibung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisbeschreibung', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisbeschreibung' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    ereignisdatum_ende_iso: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisDatum_Ende_ISO', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisdatum-ende-iso', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisdatum-ende-iso' })
    ereignis_deutschername: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignis_DeutscherName', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignis-deutschername', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignis-deutschername' })
    ereignisort_wikidata_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisOrt_Wikidata_ID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisort-wikidata-id', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisort-wikidata-id' })
    ereignisdatum_beginn_iso: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisDatum_Beginn_ISO', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisdatum-beginn-iso', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisdatum-beginn-iso' })
    ereignisinterner_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EreignisInterner Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignisinterner-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignisinterner-kommentar' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })
    informationstr_ger_externe_inventarsignaturnummer_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Externe InventarSignaturnummer_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-externe-inventarsignaturnummer-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-externe-inventarsignaturnummer-fk' })

@dataclass
class C04HfmAkteurin:
    """Dataset 04_hfm_Akteurin (canonical http://arkumu.org/data/hmt/types/04-hfm-akteurin)"""
    gnd: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'GND', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/gnd', 'local_uri': 'http://arkumu.org/data/hmt/properties/gnd' })
    loc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'LOC', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/loc', 'local_uri': 'http://arkumu.org/data/hmt/properties/loc' })
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    viaf: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'VIAF', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/viaf', 'local_uri': 'http://arkumu.org/data/hmt/properties/viaf' })
    wikidata: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Wikidata', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/wikidata', 'local_uri': 'http://arkumu.org/data/hmt/properties/wikidata' })
    akteurin_name: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Akteurin_Name', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/akteurin-name', 'local_uri': 'http://arkumu.org/data/hmt/properties/akteurin-name' })
    hfmt_akteur_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Akteur_ID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-akteur-id', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-akteur-id' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    interner_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Interner Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C06HfmKoerperschaften:
    """Dataset 06_hfm_Koerperschaften (canonical http://arkumu.org/data/hmt/types/06-hfm-koerperschaften)"""
    gnd: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'GND', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/gnd', 'local_uri': 'http://arkumu.org/data/hmt/properties/gnd' })
    loc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'LOC', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/loc', 'local_uri': 'http://arkumu.org/data/hmt/properties/loc' })
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    viaf: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'VIAF', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/viaf', 'local_uri': 'http://arkumu.org/data/hmt/properties/viaf' })
    wikidata: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Wikidata', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/wikidata', 'local_uri': 'http://arkumu.org/data/hmt/properties/wikidata' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    interner_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Interner Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/interner-kommentar' })
    koerperschaft_name: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Koerperschaft_Name', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/koerperschaft-name', 'local_uri': 'http://arkumu.org/data/hmt/properties/koerperschaft-name' })
    hfmt_k_rperschaft_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HfMT_Körperschaft_ID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-koerperschaft-id', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-koerperschaft-id' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    koerperschaften_alternative_namen: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Koerperschaften_Alternative_Namen', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/koerperschaften-alternative-namen', 'local_uri': 'http://arkumu.org/data/hmt/properties/koerperschaften-alternative-namen' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C08HfmDigitalesObjekt:
    """Dataset 08_hfm_Digitales_Objekt (canonical http://arkumu.org/data/hmt/types/08-hfm-digitales-objekt)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    entstehung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Entstehung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/entstehung', 'local_uri': 'http://arkumu.org/data/hmt/properties/entstehung' })
    erhaltungstyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Erhaltungstyp', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/erhaltungstyp', 'local_uri': 'http://arkumu.org/data/hmt/properties/erhaltungstyp' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    dateipfad_absolut: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_absolut', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/dateipfad-absolut', 'local_uri': 'http://arkumu.org/data/hmt/properties/dateipfad-absolut' })
    pruefsumme_sha256: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Pruefsumme_SHA256', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/pruefsumme-sha256', 'local_uri': 'http://arkumu.org/data/hmt/properties/pruefsumme-sha256' })
    ist_arkumu_preview: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_ist_arkumu_Preview', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ist-arkumu-preview', 'local_uri': 'http://arkumu.org/data/hmt/properties/ist-arkumu-preview' })
    arkumu_lizenzstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_Lizenzstatus', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/arkumu-lizenzstatus', 'local_uri': 'http://arkumu.org/data/hmt/properties/arkumu-lizenzstatus' })
    digitalesobjekt_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DigitalesObjekt_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/digitalesobjekt-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/digitalesobjekt-id-pk' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    digitales_objekt_dateiname: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Digitales Objekt_Dateiname', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/digitales-objekt-dateiname', 'local_uri': 'http://arkumu.org/data/hmt/properties/digitales-objekt-dateiname' })
    digitales_objekt_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Digitales Objekt_Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/digitales-objekt-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/digitales-objekt-kommentar' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C09HfmInformationstraeger:
    """Dataset 09_hfm_Informationstraeger (canonical http://arkumu.org/data/hmt/types/09-hfm-informationstraeger)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    informationstraeger_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationstraeger_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-id-pk' })
    informationstr_ger_beschreibung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Beschreibung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-beschreibung', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-beschreibung' })
    informationstr_ger_deutscher_kommentar: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Deutscher_Kommentar', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-deutscher-kommentar', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-deutscher-kommentar' })
    informationstr_ger_informationstr_gertyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Informationsträgertyp', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegertyp', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegertyp' })
    informationstr_ger_signatur_beim_einlieferer: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Signatur beim Einlieferer', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-signatur-beim-einlieferer', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-signatur-beim-einlieferer' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })
    informationstr_ger_externe_inventarsignaturnummer: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Externe InventarSignaturnummer', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-externe-inventarsignaturnummer', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-externe-inventarsignaturnummer' })
    informationstr_ger_informationstr_gereigenschaft_tonformat: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Informationsträgereigenschaft_Tonformat', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegereigenschaft-tonformat', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegereigenschaft-tonformat' })
    informationstr_ger_informationstr_gereigenschaften_abspielgeschwindigkeit: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Informationsträger_Informationsträgereigenschaften_Abspielgeschwindigkeit', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegereigenschaften-abspielgeschwindigkeit', 'local_uri': 'http://arkumu.org/data/hmt/properties/informationstraeger-informationstraegereigenschaften-abspielgeschwindigkeit' })

@dataclass
class C01HfmKreuzProjektEreignis:
    """Dataset 01_hfm_Kreuz_Projekt_Ereignis (canonical http://arkumu.org/data/hmt/types/01-hfm-kreuz-projekt-ereignis)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    ereignis_nr_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignis_Nr_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk' })
    hfmt_werk_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Werk_ID_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    kreuz_projekt_ereignis_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Projekt_Ereignis_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/kreuz-projekt-ereignis-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/kreuz-projekt-ereignis-id-pk' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C03HfmKreuzEreignisAkteure:
    """Dataset 03_hfm_Kreuz_Ereignis_Akteure (canonical http://arkumu.org/data/hmt/types/03-hfm-kreuz-ereignis-akteure)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    rolle: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Rolle', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/rolle', 'local_uri': 'http://arkumu.org/data/hmt/properties/rolle' })
    ereignis_nr_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignis_Nr_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    hfmt_akteur_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Akteur_ID_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-akteur-id-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-akteur-id-fk' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    kreuz_ereignis_akteurin_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Ereignis_Akteurin_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-akteurin-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-akteurin-id-pk' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C10HfmKreuzProjektOberwerk:
    """Dataset 10_hfm_Kreuz_Projekt_Oberwerk (canonical http://arkumu.org/data/hmt/types/10-hfm-kreuz-projekt-oberwerk)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    beziehung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Beziehung', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/beziehung', 'local_uri': 'http://arkumu.org/data/hmt/properties/beziehung' })
    hfmt_werk_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Werk_ID_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    hfmt_werk_id_2_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Werk_ID_2_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-2-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-werk-id-2-fk' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    kreuz_projekt_oberwerk_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Projekt_Oberwerk_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/kreuz-projekt-oberwerk-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/kreuz-projekt-oberwerk-id-pk' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C05HfmKreuzEreignisKoerperschaften:
    """Dataset 05_hfm_Kreuz_Ereignis_Koerperschaften (canonical http://arkumu.org/data/hmt/types/05-hfm-kreuz-ereignis-koerperschaften)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    rolle: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Rolle', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/rolle', 'local_uri': 'http://arkumu.org/data/hmt/properties/rolle' })
    ereignis_nr_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignis_Nr_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    hfmt_koerperschaft_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'HFMT_Koerperschaft_ID_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/hfmt-koerperschaft-id-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/hfmt-koerperschaft-id-fk' })
    kreuz_ereignis_koerperschaft_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Ereignis_Koerperschaft_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-koerperschaft-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-koerperschaft-id-pk' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })

@dataclass
class C07HfmKreuzEreignisDigitalesobjekt:
    """Dataset 07_hfm_Kreuz_Ereignis_DigitalesObjekt (canonical http://arkumu.org/data/hmt/types/07-hfm-kreuz-ereignis-digitalesobjekt)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/uuid', 'local_uri': 'http://arkumu.org/data/hmt/properties/uuid' })
    ereignis_nr_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignis_Nr_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/ereignis-nr-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-created' })
    digitalesobjekt_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DigitalesObjekt_ID_fk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/digitalesobjekt-id-fk', 'local_uri': 'http://arkumu.org/data/hmt/properties/digitalesobjekt-id-fk' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/hmt/properties/sql-ts-lastmodified' })
    kreuz_ereignis_digitalesobjekt_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Ereignis_DigitalesObjekt_ID_pk', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-digitalesobjekt-id-pk', 'local_uri': 'http://arkumu.org/data/hmt/properties/kreuz-ereignis-digitalesobjekt-id-pk' })
    exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/hmt/properties/exportvariablen-arkumu-timestamp-of-this-export' })
