"""Auto-generated from schema manifest."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class C00Projekte:
    """Dataset 00_Projekte (canonical http://arkumu.org/data/khm/types/00-projekte)"""
    projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-id' })
    projekt_nr: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_Nr', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-nr', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-nr' })
    untertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Untertitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/untertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/untertitel' })
    l_nge_dauer: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Länge_Dauer', 'canonical_uri': 'http://arkumu.org/data/khm/properties/laenge-dauer', 'local_uri': 'http://arkumu.org/data/khm/properties/laenge-dauer' })
    projekt_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-uuid' })
    f_chergruppe: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Fächergruppe', 'canonical_uri': 'http://arkumu.org/data/khm/properties/faechergruppe', 'local_uri': 'http://arkumu.org/data/khm/properties/faechergruppe' })
    originaltitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Originaltitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/originaltitel', 'local_uri': 'http://arkumu.org/data/khm/properties/originaltitel' })
    projektart_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projektart_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projektart-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/projektart-calc' })
    projekt_website1: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_Website1', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-website1', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-website1' })
    projekt_website2: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_Website2', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-website2', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-website2' })
    untertitel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Untertitel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/untertitel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/untertitel-sprache' })
    sql_pr_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_Pr_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pr-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pr-aenderungsts' })
    kurzinformation_engl: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kurzinformation_engl', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kurzinformation-engl', 'local_uri': 'http://arkumu.org/data/khm/properties/kurzinformation-engl' })
    sql_pr_erstellungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_Pr_ErstellungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pr-erstellungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pr-erstellungsts' })
    originaltitel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Originaltitel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/originaltitel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/originaltitel-sprache' })
    beschreibung_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Beschreibung_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/beschreibung-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/beschreibung-verkettet' })
    technisches_produktionsformat: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Technisches Produktionsformat', 'canonical_uri': 'http://arkumu.org/data/khm/properties/technisches-produktionsformat', 'local_uri': 'http://arkumu.org/data/khm/properties/technisches-produktionsformat' })
    titel_erster_alternativer_titel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_erster_alternativer_Titel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-titel', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-titel' })
    titel_zweiter_alternativer_titel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_zweiter_alternativer_Titel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-titel', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-titel' })
    aspect_ratio_bildseitenverh_ltnis: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Aspect_Ratio_Bildseitenverhältnis', 'canonical_uri': 'http://arkumu.org/data/khm/properties/aspect-ratio-bildseitenverhaeltnis', 'local_uri': 'http://arkumu.org/data/khm/properties/aspect-ratio-bildseitenverhaeltnis' })
    titel_erster_alternativer_untertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_erster_alternativer_Untertitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-untertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-untertitel' })
    titel_zweiter_alternativer_untertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_zweiter_alternativer_Untertitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-untertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-untertitel' })
    titel_erster_alternativer_titel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_erster_alternativer_Titel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-titel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-titel-sprache' })
    titel_zweiter_alternativer_titel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_zweiter_alternativer_Titel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-titel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-titel-sprache' })
    projekte_export_projektkategorien_arkumu: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Export_Projektkategorien_arkumu', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-export-projektkategorien-arkumu', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-export-projektkategorien-arkumu' })
    titel_erster_alternativer_untertitel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_erster_alternativer_Untertitel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-untertitel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-erster-alternativer-untertitel-sprache' })
    globale_exportvariablen_arkumu_rechtsstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Rechtsstatus', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-rechtsstatus', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-rechtsstatus' })
    titel_zweiter_alternativer_untertitel_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Titel_zweiter_alternativer_Untertitel_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-untertitel-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/titel-zweiter-alternativer-untertitel-sprache' })
    globale_exportvariablen_arkumu_art_des_lizenzvertrages: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Art des Lizenzvertrages', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-art-des-lizenzvertrages', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-art-des-lizenzvertrages' })
    globale_exportvariablen_arkumu_einliefernde_hochschule: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Einliefernde Hochschule', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-einliefernde-hochschule', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-einliefernde-hochschule' })
    globale_exportvariablen_arkumu_timestamp_of_this_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Timestamp_of_this_export', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-timestamp-of-this-export', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-timestamp-of-this-export' })
    globale_exportvariablen_arkumu_bestehender_lizenzvertrag: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Bestehender Lizenzvertrag', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-bestehender-lizenzvertrag', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-bestehender-lizenzvertrag' })

@dataclass
class C08Keywords:
    """Dataset 08_Keywords (canonical http://arkumu.org/data/khm/types/08-keywords)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    keyword_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Keyword_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/keyword-id', 'local_uri': 'http://arkumu.org/data/khm/properties/keyword-id' })
    keyword_deu: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Keyword_deu', 'canonical_uri': 'http://arkumu.org/data/khm/properties/keyword-deu', 'local_uri': 'http://arkumu.org/data/khm/properties/keyword-deu' })
    keyword_eng: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Keyword_eng', 'canonical_uri': 'http://arkumu.org/data/khm/properties/keyword-eng', 'local_uri': 'http://arkumu.org/data/khm/properties/keyword-eng' })
    wikidata_qid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Wikidata_QID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid', 'local_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C20Equipmentart:
    """Dataset 20_Equipmentart (canonical http://arkumu.org/data/khm/types/20-equipmentart)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    aat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'AAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/aat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/aat-id' })
    gnd_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'GND_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/gnd-id', 'local_uri': 'http://arkumu.org/data/khm/properties/gnd-id' })
    wikidata_qid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Wikidata_QID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid', 'local_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid' })
    equipmentart_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipmentart_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipmentart-id', 'local_uri': 'http://arkumu.org/data/khm/properties/equipmentart-id' })
    equipmentart_deu: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipmentart_deu', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipmentart-deu', 'local_uri': 'http://arkumu.org/data/khm/properties/equipmentart-deu' })
    equipmentart_eng: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipmentart_eng', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipmentart-eng', 'local_uri': 'http://arkumu.org/data/khm/properties/equipmentart-eng' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C01Grundereignis:
    """Dataset 01_Grundereignis (canonical http://arkumu.org/data/khm/types/01-grundereignis)"""
    projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-id' })
    projekt_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-uuid' })
    entstehungsjahr: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Entstehungsjahr', 'canonical_uri': 'http://arkumu.org/data/khm/properties/entstehungsjahr', 'local_uri': 'http://arkumu.org/data/khm/properties/entstehungsjahr' })
    arkumu_ereignistyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'arkumu_Ereignistyp', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-ereignistyp', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-ereignistyp' })
    sql_pr_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_Pr_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pr-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pr-aenderungsts' })
    sql_pr_erstellungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_Pr_ErstellungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pr-erstellungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pr-erstellungsts' })
    jahr_der_fertigstellung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Jahr der Fertigstellung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/jahr-der-fertigstellung', 'local_uri': 'http://arkumu.org/data/khm/properties/jahr-der-fertigstellung' })
    ereignisherstellungbeschreibung_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_EreignisHerstellungBeschreibung_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ereignisherstellungbeschreibung-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/ereignisherstellungbeschreibung-verkettet' })
    projekte_export_ereignisherstellung_deutschername: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Export_EreignisHerstellung_DeutscherName', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-export-ereignisherstellung-deutschername', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-export-ereignisherstellung-deutschername' })
    projekte_export_entstehungs_und_produktionsland_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Export_Entstehungs_und_Produktionsland_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-export-entstehungs-und-produktionsland-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-export-entstehungs-und-produktionsland-verkettet' })

@dataclass
class C12cVorschaubild:
    """Dataset 12c_Vorschaubild (canonical http://arkumu.org/data/khm/types/12c-vorschaubild)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    dat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/dat-id' })
    dateipfad_absolut: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_absolut', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut' })
    ist_vorschaubild: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_ist_Vorschaubild', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ist-vorschaubild', 'local_uri': 'http://arkumu.org/data/khm/properties/ist-vorschaubild' })
    ist_arkumu_preview: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_ist_arkumu_Preview', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ist-arkumu-preview', 'local_uri': 'http://arkumu.org/data/khm/properties/ist-arkumu-preview' })
    dateiname_arkumu_web: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateiname_arkumu_web', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web', 'local_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web' })
    arkumu_lizenzstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_Lizenzstatus', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus' })
    arkumu_preview_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_preview_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-preview-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-preview-uuid' })
    projekte_export_projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Export_Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-export-projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-export-projekt-id' })
    projekte_export_vorschaubild_dat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Projekte_Export_Vorschaubild_DAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-export-vorschaubild-dat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-export-vorschaubild-dat-id' })
    globale_exportvariablen_arkumu_erhaltungstyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Erhaltungstyp', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-erhaltungstyp', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-erhaltungstyp' })

@dataclass
class C12bArkumuPreviews:
    """Dataset 12b_arkumu_previews (canonical http://arkumu.org/data/khm/types/12b-arkumu-previews)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    dat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/dat-id' })
    dateipfad_absolut: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_absolut', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut' })
    ist_arkumu_preview: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_ist_arkumu_Preview', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ist-arkumu-preview', 'local_uri': 'http://arkumu.org/data/khm/properties/ist-arkumu-preview' })
    dateiname_arkumu_web: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateiname_arkumu_web', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web', 'local_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web' })
    arkumu_lizenzstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_Lizenzstatus', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus' })
    arkumu_preview_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_preview_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-preview-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-preview-uuid' })

@dataclass
class C21Physischesobjekt:
    """Dataset 21_PhysischesObjekt (canonical http://arkumu.org/data/khm/types/21-physischesobjekt)"""
    projekte_projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-id' })
    projekte_projekt_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Projekt_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-uuid' })
    projekte_material_qids_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Material_QIDs_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-material-qids-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-material-qids-calc' })
    projekte_material_titel_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Material_Titel_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-material-titel-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-material-titel-calc' })
    projekte_sql_pr_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_SQL_Pr_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-sql-pr-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-sql-pr-aenderungsts' })
    projekte_sql_pr_erstellungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_SQL_Pr_ErstellungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-sql-pr-erstellungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-sql-pr-erstellungsts' })
    projekte_masse_umfang_dimension: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Masse_Umfang_Dimension', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-masse-umfang-dimension', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-masse-umfang-dimension' })
    projekte_material_beschreibung_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Material_Beschreibung_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-material-beschreibung-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-material-beschreibung-calc' })

@dataclass
class C05Personenbetreuende:
    """Dataset 05_PersonenBetreuende (canonical http://arkumu.org/data/khm/types/05-personenbetreuende)"""
    pe_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-id', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-id' })
    pe_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-uuid' })
    pe_homepage1: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Homepage1', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-homepage1', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-homepage1' })
    pe_homepage2: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Homepage2', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-homepage2', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-homepage2' })
    pe_normdatum_gnd: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_GND', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-gnd', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-gnd' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    pe_normdatum_lccn: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_LCCN', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-lccn', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-lccn' })
    pe_normdatum_viaf: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_VIAF', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-viaf', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-viaf' })
    pe_normdatum_orcid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_ORCID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-orcid', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-orcid' })
    pe_normdatum_andere: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_andere', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-andere', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-andere' })
    sql_pe_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_PE_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pe-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pe-aenderungsts' })
    nachgestelltertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'nachgestellterTitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/nachgestelltertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/nachgestelltertitel' })
    vorangestelltertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'vorangestellterTitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/vorangestelltertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/vorangestelltertitel' })
    pe_normdatum_wikidata: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_Wikidata', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-wikidata', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-wikidata' })
    nicht_ffentlicher_name: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'nicht_öffentlicher_Name', 'canonical_uri': 'http://arkumu.org/data/khm/properties/nicht-oeffentlicher-name', 'local_uri': 'http://arkumu.org/data/khm/properties/nicht-oeffentlicher-name' })
    name_gesamt_nat_rlichereihenfolge_calc_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Name_gesamt_natürlicheReihenfolge_calc_export', 'canonical_uri': 'http://arkumu.org/data/khm/properties/name-gesamt-natuerlichereihenfolge-calc-export', 'local_uri': 'http://arkumu.org/data/khm/properties/name-gesamt-natuerlichereihenfolge-calc-export' })

@dataclass
class C03PersonenAkteurinnen:
    """Dataset 03_Personen_Akteurinnen (canonical http://arkumu.org/data/khm/types/03-personen-akteurinnen)"""
    pe_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-id', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-id' })
    pe_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-uuid' })
    pe_homepage1: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Homepage1', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-homepage1', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-homepage1' })
    pe_homepage2: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Homepage2', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-homepage2', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-homepage2' })
    pe_normdatum_gnd: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_GND', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-gnd', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-gnd' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    pe_normdatum_lccn: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_LCCN', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-lccn', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-lccn' })
    pe_normdatum_viaf: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_VIAF', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-viaf', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-viaf' })
    pe_normdatum_orcid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_ORCID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-orcid', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-orcid' })
    pe_normdatum_andere: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_andere', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-andere', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-andere' })
    sql_pe_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_PE_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-pe-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-pe-aenderungsts' })
    nachgestelltertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'nachgestellterTitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/nachgestelltertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/nachgestelltertitel' })
    vorangestelltertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'vorangestellterTitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/vorangestelltertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/vorangestelltertitel' })
    pe_normdatum_wikidata: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_Normdatum_Wikidata', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-wikidata', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-normdatum-wikidata' })
    nicht_ffentlicher_name: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'nicht_öffentlicher_Name', 'canonical_uri': 'http://arkumu.org/data/khm/properties/nicht-oeffentlicher-name', 'local_uri': 'http://arkumu.org/data/khm/properties/nicht-oeffentlicher-name' })
    name_gesamt_nat_rlichereihenfolge_calc_export: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Name_gesamt_natürlicheReihenfolge_calc_export', 'canonical_uri': 'http://arkumu.org/data/khm/properties/name-gesamt-natuerlichereihenfolge-calc-export', 'local_uri': 'http://arkumu.org/data/khm/properties/name-gesamt-natuerlichereihenfolge-calc-export' })

@dataclass
class C12MediaDigitaleobjekte:
    """Dataset 12_Media_DigitaleObjekte (canonical http://arkumu.org/data/khm/types/12-media-digitaleobjekte)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    dat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/dat-id' })
    bildart: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bildart', 'canonical_uri': 'http://arkumu.org/data/khm/properties/bildart', 'local_uri': 'http://arkumu.org/data/khm/properties/bildart' })
    framerate: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Framerate', 'canonical_uri': 'http://arkumu.org/data/khm/properties/framerate', 'local_uri': 'http://arkumu.org/data/khm/properties/framerate' })
    entstehung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Entstehung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/entstehung', 'local_uri': 'http://arkumu.org/data/khm/properties/entstehung' })
    pub_status: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Pub_Status', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pub-status', 'local_uri': 'http://arkumu.org/data/khm/properties/pub-status' })
    dateityp_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateityp_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateityp-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/dateityp-calc' })
    dateipfad_kurz: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad kurz', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-kurz', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-kurz' })
    sql_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-aenderungsts' })
    dateipfad_absolut: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_absolut', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut' })
    pruefsumme_sha256: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Pruefsumme_SHA256', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pruefsumme-sha256', 'local_uri': 'http://arkumu.org/data/khm/properties/pruefsumme-sha256' })
    sql_erstellungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_ErstellungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-erstellungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-erstellungsts' })
    erhaltungstyp_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Erhaltungstyp_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/erhaltungstyp-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/erhaltungstyp-calc' })
    dateiname_arkumu_web: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateiname_arkumu_web', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web', 'local_uri': 'http://arkumu.org/data/khm/properties/dateiname-arkumu-web' })
    dateipfad_dcp_ordner: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_DCP_Ordner', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-dcp-ordner', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-dcp-ordner' })
    arkumu_lizenzstatus: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_arkumu_Lizenzstatus', 'canonical_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus', 'local_uri': 'http://arkumu.org/data/khm/properties/arkumu-lizenzstatus' })
    description_de_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Description_DE_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/description-de-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/description-de-verkettet' })
    description_en_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Description_EN_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/description-en-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/description-en-verkettet' })

@dataclass
class C16KreuzEventsProjekte:
    """Dataset 16_Kreuz_Events_Projekte (canonical http://arkumu.org/data/khm/types/16-kreuz-events-projekte)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    kr_proj_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kr_Proj_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kr-proj-id', 'local_uri': 'http://arkumu.org/data/khm/properties/kr-proj-id' })
    kr_event_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kr_Event_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kr-event-id', 'local_uri': 'http://arkumu.org/data/khm/properties/kr-event-id' })
    kr_einlad_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kr_Einlad_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kr-einlad-id', 'local_uri': 'http://arkumu.org/data/khm/properties/kr-einlad-id' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C13bTrackDigitaleobjekte:
    """Dataset 13b_Track_DigitaleObjekte (canonical http://arkumu.org/data/khm/types/13b-track-digitaleobjekte)"""
    tr_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'TR_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tr-id', 'local_uri': 'http://arkumu.org/data/khm/properties/tr-id' })
    tr_uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'TR_UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tr-uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/tr-uuid' })
    tr_sprache: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'TR_Sprache', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tr-sprache', 'local_uri': 'http://arkumu.org/data/khm/properties/tr-sprache' })
    tr_type_kurz: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'TR_Type_Kurz', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tr-type-kurz', 'local_uri': 'http://arkumu.org/data/khm/properties/tr-type-kurz' })
    dateiname_kurz: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateiname_Kurz', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateiname-kurz', 'local_uri': 'http://arkumu.org/data/khm/properties/dateiname-kurz' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    dateipfad_absolut: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Dateipfad_absolut', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut', 'local_uri': 'http://arkumu.org/data/khm/properties/dateipfad-absolut' })
    media_dateipfad_kurz: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Media_Dateipfad kurz', 'canonical_uri': 'http://arkumu.org/data/khm/properties/media-dateipfad-kurz', 'local_uri': 'http://arkumu.org/data/khm/properties/media-dateipfad-kurz' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C19EquipmentUndSoftware:
    """Dataset 19_Equipment_und_Software (canonical http://arkumu.org/data/khm/types/19-equipment-und-software)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    hersteller: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Hersteller', 'canonical_uri': 'http://arkumu.org/data/khm/properties/hersteller', 'local_uri': 'http://arkumu.org/data/khm/properties/hersteller' })
    equipment_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipment_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipment-id', 'local_uri': 'http://arkumu.org/data/khm/properties/equipment-id' })
    wikidata_qid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Wikidata_QID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid', 'local_uri': 'http://arkumu.org/data/khm/properties/wikidata-qid' })
    equipment_deu: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipment_deu', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipment-deu', 'local_uri': 'http://arkumu.org/data/khm/properties/equipment-deu' })
    equipment_eng: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipment_eng', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipment-eng', 'local_uri': 'http://arkumu.org/data/khm/properties/equipment-eng' })
    beschreibung_de: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Beschreibung_DE', 'canonical_uri': 'http://arkumu.org/data/khm/properties/beschreibung-de', 'local_uri': 'http://arkumu.org/data/khm/properties/beschreibung-de' })
    beschreibung_en: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Beschreibung_EN', 'canonical_uri': 'http://arkumu.org/data/khm/properties/beschreibung-en', 'local_uri': 'http://arkumu.org/data/khm/properties/beschreibung-en' })
    equipmentart_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipmentart_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipmentart-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/equipmentart-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C02KreuzProjektePersonen:
    """Dataset 02_Kreuz_Projekte_Personen (canonical http://arkumu.org/data/khm/types/02-kreuz-projekte-personen)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    as_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'AS_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/as-id', 'local_uri': 'http://arkumu.org/data/khm/properties/as-id' })
    as_pers_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'AS_Pers_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/as-pers-id', 'local_uri': 'http://arkumu.org/data/khm/properties/as-pers-id' })
    as_proj_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'AS_Proj_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/as-proj-id', 'local_uri': 'http://arkumu.org/data/khm/properties/as-proj-id' })
    ist_urheberin: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'ist_Urheberin', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ist-urheberin', 'local_uri': 'http://arkumu.org/data/khm/properties/ist-urheberin' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    as_taetigkeit_arkumu_rolle: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'AS_Taetigkeit_arkumu_Rolle', 'canonical_uri': 'http://arkumu.org/data/khm/properties/as-taetigkeit-arkumu-rolle', 'local_uri': 'http://arkumu.org/data/khm/properties/as-taetigkeit-arkumu-rolle' })
    besitzt_leistungsschutzrechte: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'besitzt_Leistungsschutzrechte', 'canonical_uri': 'http://arkumu.org/data/khm/properties/besitzt-leistungsschutzrechte', 'local_uri': 'http://arkumu.org/data/khm/properties/besitzt-leistungsschutzrechte' })

@dataclass
class C06AuszeichnungenProjekte:
    """Dataset 06_Auszeichnungen_Projekte (canonical http://arkumu.org/data/khm/types/06-auszeichnungen-projekte)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    ausz_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ausz_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ausz-id', 'local_uri': 'http://arkumu.org/data/khm/properties/ausz-id' })
    ausz_ende: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ausz_Ende', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ausz-ende', 'local_uri': 'http://arkumu.org/data/khm/properties/ausz-ende' })
    ausz_name: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ausz_Name', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ausz-name', 'local_uri': 'http://arkumu.org/data/khm/properties/ausz-name' })
    ausz_anfang: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ausz_Anfang', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ausz-anfang', 'local_uri': 'http://arkumu.org/data/khm/properties/ausz-anfang' })
    ausz_proj_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ausz_Proj_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ausz-proj-id', 'local_uri': 'http://arkumu.org/data/khm/properties/ausz-proj-id' })
    sql_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-aenderungsts' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    beschreibung_verkettet: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_Beschreibung_verkettet', 'canonical_uri': 'http://arkumu.org/data/khm/properties/beschreibung-verkettet', 'local_uri': 'http://arkumu.org/data/khm/properties/beschreibung-verkettet' })
    globale_exportvariablen_arkumu_ereignistyp_auszeichnung: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Ereignistyp_Auszeichnung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-ereignistyp-auszeichnung', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-ereignistyp-auszeichnung' })

@dataclass
class C07KreuzProjekteKeywords:
    """Dataset 07_Kreuz_Projekte_Keywords (canonical http://arkumu.org/data/khm/types/07-kreuz-projekte-keywords)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    proj_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Proj_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk' })
    keyword_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Keyword_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/keyword-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/keyword-id-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    kreuz_projekte_keywords_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Projekte_Keywords_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kreuz-projekte-keywords-id', 'local_uri': 'http://arkumu.org/data/khm/properties/kreuz-projekte-keywords-id' })

@dataclass
class C17EventsWeitereereignisse:
    """Dataset 17_Events_weitereEreignisse (canonical http://arkumu.org/data/khm/types/17-events-weitereereignisse)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    website: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'website', 'canonical_uri': 'http://arkumu.org/data/khm/properties/website', 'local_uri': 'http://arkumu.org/data/khm/properties/website' })
    event_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Event_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/event-id', 'local_uri': 'http://arkumu.org/data/khm/properties/event-id' })
    eventname: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Eventname', 'canonical_uri': 'http://arkumu.org/data/khm/properties/eventname', 'local_uri': 'http://arkumu.org/data/khm/properties/eventname' })
    ereignistyp: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ereignistyp', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ereignistyp', 'local_uri': 'http://arkumu.org/data/khm/properties/ereignistyp' })
    ort_wikidata_qid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Ort_Wikidata_QID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ort-wikidata-qid', 'local_uri': 'http://arkumu.org/data/khm/properties/ort-wikidata-qid' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    eventenddatum_iso: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'EventEnddatum_ISO', 'canonical_uri': 'http://arkumu.org/data/khm/properties/eventenddatum-iso', 'local_uri': 'http://arkumu.org/data/khm/properties/eventenddatum-iso' })
    sql_ev_aenderungsts: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'SQL_Ev_AenderungsTS', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ev-aenderungsts', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ev-aenderungsts' })
    eventanfangsdatum_iso: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Eventanfangsdatum_ISO', 'canonical_uri': 'http://arkumu.org/data/khm/properties/eventanfangsdatum-iso', 'local_uri': 'http://arkumu.org/data/khm/properties/eventanfangsdatum-iso' })

@dataclass
class C04KreuzBetreuendeProjekte:
    """Dataset 04_Kreuz_Betreuende_Projekte (canonical http://arkumu.org/data/khm/types/04-kreuz-betreuende-projekte)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    pe_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PE_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/pe-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/pe-id-fk' })
    proj_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Proj_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk' })
    ist_urheberin: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'ist_Urheberin', 'canonical_uri': 'http://arkumu.org/data/khm/properties/ist-urheberin', 'local_uri': 'http://arkumu.org/data/khm/properties/ist-urheberin' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    kreuz_lehrende_proj_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Lehrende_Proj_ID_pk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kreuz-lehrende-proj-id-pk', 'local_uri': 'http://arkumu.org/data/khm/properties/kreuz-lehrende-proj-id-pk' })
    besitzt_leistungsschutzrechte: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'besitzt_Leistungsschutzrechte', 'canonical_uri': 'http://arkumu.org/data/khm/properties/besitzt-leistungsschutzrechte', 'local_uri': 'http://arkumu.org/data/khm/properties/besitzt-leistungsschutzrechte' })
    globale_exportvariablen_arkumu_rolle: list[str] = field(default_factory=list, metadata={ 'dataset_property': '_globale_Exportvariablen_arkumu_Rolle', 'canonical_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-rolle', 'local_uri': 'http://arkumu.org/data/khm/properties/globale-exportvariablen-arkumu-rolle' })

@dataclass
class C11KreuzDigitaleobjekteProj:
    """Dataset 11_Kreuz_DigitaleObjekte_Proj (canonical http://arkumu.org/data/khm/types/11-kreuz-digitaleobjekte-proj)"""
    id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/id', 'local_uri': 'http://arkumu.org/data/khm/properties/id' })
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    dat_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'DAT_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/dat-id', 'local_uri': 'http://arkumu.org/data/khm/properties/dat-id' })
    projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekt-id' })
    med_freigabe: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Med_Freigabe', 'canonical_uri': 'http://arkumu.org/data/khm/properties/med-freigabe', 'local_uri': 'http://arkumu.org/data/khm/properties/med-freigabe' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    zaehler_media_proj: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Zaehler_Media_Proj', 'canonical_uri': 'http://arkumu.org/data/khm/properties/zaehler-media-proj', 'local_uri': 'http://arkumu.org/data/khm/properties/zaehler-media-proj' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })

@dataclass
class C13aKreuztabelleTrackProjekt:
    """Dataset 13a_Kreuztabelle_Track_Projekt (canonical http://arkumu.org/data/khm/types/13a-kreuztabelle-track-projekt)"""
    tr_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'TR_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tr-id', 'local_uri': 'http://arkumu.org/data/khm/properties/tr-id' })
    projekte_projekt_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Projekte_Projekt_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-id', 'local_uri': 'http://arkumu.org/data/khm/properties/projekte-projekt-id' })

@dataclass
class C10PhysmedienInformationstraeger:
    """Dataset 10_PhysMedien_Informationstraeger (canonical http://arkumu.org/data/khm/types/10-physmedien-informationstraeger)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    signatur: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Signatur', 'canonical_uri': 'http://arkumu.org/data/khm/properties/signatur', 'local_uri': 'http://arkumu.org/data/khm/properties/signatur' })
    tonformat: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Tonformat', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tonformat', 'local_uri': 'http://arkumu.org/data/khm/properties/tonformat' })
    videonorm: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Videonorm', 'canonical_uri': 'http://arkumu.org/data/khm/properties/videonorm', 'local_uri': 'http://arkumu.org/data/khm/properties/videonorm' })
    bemerkungen: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bemerkungen', 'canonical_uri': 'http://arkumu.org/data/khm/properties/bemerkungen', 'local_uri': 'http://arkumu.org/data/khm/properties/bemerkungen' })
    kompilation: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kompilation', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kompilation', 'local_uri': 'http://arkumu.org/data/khm/properties/kompilation' })
    bildfrequenz: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Bildfrequenz', 'canonical_uri': 'http://arkumu.org/data/khm/properties/bildfrequenz', 'local_uri': 'http://arkumu.org/data/khm/properties/bildfrequenz' })
    medienformat: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Medienformat', 'canonical_uri': 'http://arkumu.org/data/khm/properties/medienformat', 'local_uri': 'http://arkumu.org/data/khm/properties/medienformat' })
    medienzaehler: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Medienzaehler', 'canonical_uri': 'http://arkumu.org/data/khm/properties/medienzaehler', 'local_uri': 'http://arkumu.org/data/khm/properties/medienzaehler' })
    physmedien_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PhysMedien_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/physmedien-id', 'local_uri': 'http://arkumu.org/data/khm/properties/physmedien-id' })
    standort_calc: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Standort_calc', 'canonical_uri': 'http://arkumu.org/data/khm/properties/standort-calc', 'local_uri': 'http://arkumu.org/data/khm/properties/standort-calc' })
    tonmischfassung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Tonmischfassung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tonmischfassung', 'local_uri': 'http://arkumu.org/data/khm/properties/tonmischfassung' })
    filmtonverfahren: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Filmtonverfahren', 'canonical_uri': 'http://arkumu.org/data/khm/properties/filmtonverfahren', 'local_uri': 'http://arkumu.org/data/khm/properties/filmtonverfahren' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    kompilationstitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kompilationstitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kompilationstitel', 'local_uri': 'http://arkumu.org/data/khm/properties/kompilationstitel' })
    sprache_untertitel: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Sprache Untertitel', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sprache-untertitel', 'local_uri': 'http://arkumu.org/data/khm/properties/sprache-untertitel' })
    kompilationszaehler: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kompilationszaehler', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kompilationszaehler', 'local_uri': 'http://arkumu.org/data/khm/properties/kompilationszaehler' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    synchronisationsfassung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Synchronisationsfassung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/synchronisationsfassung', 'local_uri': 'http://arkumu.org/data/khm/properties/synchronisationsfassung' })
    tc_info_aus_kreuztabelle: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__TC_Info_aus_Kreuztabelle', 'canonical_uri': 'http://arkumu.org/data/khm/properties/tc-info-aus-kreuztabelle', 'local_uri': 'http://arkumu.org/data/khm/properties/tc-info-aus-kreuztabelle' })
    sprache_der_originalfassung: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Sprache der Originalfassung', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sprache-der-originalfassung', 'local_uri': 'http://arkumu.org/data/khm/properties/sprache-der-originalfassung' })
    aspect_ratio_bildseitenverh_ltnis: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Aspect_Ratio_Bildseitenverhältnis', 'canonical_uri': 'http://arkumu.org/data/khm/properties/aspect-ratio-bildseitenverhaeltnis', 'local_uri': 'http://arkumu.org/data/khm/properties/aspect-ratio-bildseitenverhaeltnis' })

@dataclass
class C18KreuzProjekteEquipmentsoftware:
    """Dataset 18_Kreuz_Projekte_EquipmentSoftware (canonical http://arkumu.org/data/khm/types/18-kreuz-projekte-equipmentsoftware)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    proj_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Proj_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk' })
    equipment_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Equipment_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/equipment-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/equipment-id-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    kreuz_projekte_equipment_id: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_Projekte_Equipment_ID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kreuz-projekte-equipment-id', 'local_uri': 'http://arkumu.org/data/khm/properties/kreuz-projekte-equipment-id' })

@dataclass
class C09KreuzProjekteInformationstrGer:
    """Dataset 09_Kreuz_Projekte_Informationsträger (canonical http://arkumu.org/data/khm/types/09-kreuz-projekte-informationstraeger)"""
    uuid: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'UUID', 'canonical_uri': 'http://arkumu.org/data/khm/properties/uuid', 'local_uri': 'http://arkumu.org/data/khm/properties/uuid' })
    proj_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Proj_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/proj-id-fk' })
    physmedien_id_fk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'PhysMedien_ID_fk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/physmedien-id-fk', 'local_uri': 'http://arkumu.org/data/khm/properties/physmedien-id-fk' })
    sql_ts_created: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_Created', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-created' })
    sql_ts_lastmodified: list[str] = field(default_factory=list, metadata={ 'dataset_property': '__SQL_TS_LastModified', 'canonical_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified', 'local_uri': 'http://arkumu.org/data/khm/properties/sql-ts-lastmodified' })
    kreuz_physmedien_proj_id_pk: list[str] = field(default_factory=list, metadata={ 'dataset_property': 'Kreuz_PhysMedien_Proj_ID_pk', 'canonical_uri': 'http://arkumu.org/data/khm/properties/kreuz-physmedien-proj-id-pk', 'local_uri': 'http://arkumu.org/data/khm/properties/kreuz-physmedien-proj-id-pk' })
