# Generated by Django 5.0.11 on 2025-11-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0014_merge_20251107_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAIProjectMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('project', 'Project'), ('event', 'Event'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('order_index', models.PositiveIntegerField(blank=True, help_text='Explicit ordering applied when emitting METS structMap/fileSec entries.', null=True)),
                ('label_override', models.CharField(blank=True, help_text='Curator-provided display label for the digital object.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Free-form curator notes.')),
                ('is_stale', models.BooleanField(default=False, help_text='Flagged when the canonical graph no longer references this digital object.')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oai_media_references', to='metadata.resource')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oai_media_links_reviewed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oai_media_links', to='metadata.resource')),
            ],
            options={
                'verbose_name': 'OAI Project Media Link',
                'verbose_name_plural': 'OAI Project Media Links',
                'indexes': [models.Index(fields=['project'], name='oai_media_project_idx'), models.Index(fields=['digital_object'], name='oai_media_object_idx'), models.Index(fields=['status'], name='oai_media_status_idx'), models.Index(fields=['is_stale'], name='oai_media_stale_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oaiprojectmedialink',
            constraint=models.UniqueConstraint(fields=('project', 'digital_object'), name='uniq_oai_media_link_project_object'),
        ),
    ]
