# Generated by Django 5.0.11 on 2025-11-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0003_remove_oaiprojectpublication_notes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAIMediaSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('canonical', 'Canonical'), ('tailored', 'Tailored')], default='tailored', max_length=20)),
                ('last_seed_at', models.DateTimeField(blank=True, null=True)),
                ('last_publication_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oai_media_sync_states', to='users.organization')),
            ],
            options={
                'verbose_name': 'OAI Media Sync State',
                'verbose_name_plural': 'OAI Media Sync States',
                'unique_together': {('organization', 'profile')},
            },
        ),
    ]
