# Generated by Django 5.0.11 on 2025-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0004_oaimediasyncstate'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='oaiprojectmedialink',
            name='oai_media_status_idx',
        ),
        migrations.RemoveField(
            model_name='oaiprojectmedialink',
            name='status',
        ),
    ]
