# Generated by Django 5.0.11 on 2025-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0005_remove_oaiprojectmedialink_oai_media_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAIDcpPathIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=16)),
                ('bundle_key', models.TextField(help_text="Canonical relative identifier for the DCP folder (e.g. '2265_auf_der_strecke_dcp').")),
                ('folder_name', models.CharField(help_text="Last segment of the DCP directory (e.g. '2265_auf_der_strecke_dcp').", max_length=255)),
                ('relative_file_path', models.TextField(help_text="File path relative to the Rosetta root (e.g. '2265_auf_der_strecke_dcp/asset.mxf').")),
                ('file_name', models.CharField(help_text='Basename of the file within the DCP bundle.', max_length=255)),
            ],
            options={
                'verbose_name': 'OAI DCP Path Index',
                'verbose_name_plural': 'OAI DCP Path Index Entries',
                'indexes': [models.Index(fields=['org_code', 'bundle_key'], name='oai_dcp_bundle_key_idx'), models.Index(fields=['org_code', 'folder_name'], name='oai_dcp_folder_name_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oaidcppathindex',
            constraint=models.UniqueConstraint(fields=('org_code', 'relative_file_path'), name='uniq_oai_dcp_org_relative_path'),
        ),
    ]
