# Generated by Django 5.0.11 on 2025-12-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0006_oaidcppathindex_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAISnapshotMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(help_text='When the current snapshot was generated.')),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total number of records in the snapshot.')),
                ('counts_by_org', models.JSONField(blank=True, default=dict, help_text='Record counts by organization code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAI Snapshot Metadata',
                'verbose_name_plural': 'OAI Snapshot Metadata',
            },
        ),
        migrations.CreateModel(
            name='OAISnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, help_text='Position in the snapshot for stable pagination.')),
                ('uri', models.CharField(help_text='Project URI (OAI identifier).', max_length=512, unique=True)),
                ('datestamp', models.DateTimeField(help_text='Record datestamp for OAI header.')),
                ('header_xml', models.TextField(help_text='Serialized OAI <header> element.')),
                ('metadata_dc_xml', models.TextField(blank=True, help_text='Serialized Dublin Core <metadata> element.')),
                ('metadata_mets_xml', models.TextField(blank=True, help_text='Serialized METS <metadata> element.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oai_snapshot_records', to='users.organization')),
            ],
            options={
                'verbose_name': 'OAI Snapshot Record',
                'verbose_name_plural': 'OAI Snapshot Records',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['organization', 'position'], name='oai_snaprec_org_pos_idx')],
            },
        ),
    ]
